let masterList = [["1", "Ephesians 1:1", "Paul, an apostle of Jesus Christ by the will of God, to the saints which are at Ephesus, and to the faithful in Christ Jesus:"],
["2", "Ephesians 1:2", "Grace be to you, and peace, from God our Father, and from the Lord Jesus Christ."],
["3", "Ephesians 1:3", "Blessed be the God and Father of our Lord Jesus Christ, who hath blessed us with all spiritual blessings in heavenly places in Christ:"],
["4", "Ephesians 1:4", "According as he hath chosen us in him before the foundation of the world, that we should be holy and without blame before him in love:"],
["5", "Ephesians 1:5", "Having predestinated us unto the adoption of children by Jesus Christ to himself, according to the good pleasure of his will,"],
["6", "Ephesians 1:6", "To the praise of the glory of his grace, wherein he hath made us accepted in the beloved."],
["7", "Ephesians 1:7", "In whom we have redemption through his blood, the forgiveness of sins, according to the riches of his grace;"],
["8", "Ephesians 1:8", "Wherein he hath abounded toward us in all wisdom and prudence;"],
["9", "Ephesians 1:9", "Having made known unto us the mystery of his will, according to his good pleasure which he hath purposed in himself:"],
["10", "Ephesians 1:10", "That in the dispensation of the fulness of times he might gather together in one all things in Christ, both which are in heaven, and which are on earth; even in him:"],
["11", "Ephesians 1:11", "In whom also we have obtained an inheritance, being predestinated according to the purpose of him who worketh all things after the counsel of his own will:"],
["12", "Ephesians 1:12", "That we should be to the praise of his glory, who first trusted in Christ."],
["13", "Ephesians 1:13", "In whom ye also trusted, after that ye heard the word of truth, the gospel of your salvation: in whom also after that ye believed, ye were sealed with that holy Spirit of promise,"],
["14", "Ephesians 1:14", "Which is the earnest of our inheritance until the redemption of the purchased possession, unto the praise of his glory."],
["15", "Ephesians 1:15", "Wherefore I also, after I heard of your faith in the Lord Jesus, and love unto all the saints,"],
["16", "Ephesians 1:16", "Cease not to give thanks for you, making mention of you in my prayers;"],
["17", "Ephesians 1:17", "That the God of our Lord Jesus Christ, the Father of glory, may give unto you the spirit of wisdom and revelation in the knowledge of him:"],
["18", "Ephesians 1:18", "The eyes of your understanding being enlightened; that ye may know what is the hope of his calling, and what the riches of the glory of his inheritance in the saints,"],
["19", "Ephesians 1:19", "And what is the exceeding greatness of his power to us-ward who believe, according to the working of his mighty power,"],
["20", "Ephesians 1:20", "Which he wrought in Christ, when he raised him from the dead, and set him at his own right hand in the heavenly places,"],
["21", "Ephesians 1:21", "Far above all principality, and power, and might, and dominion, and every name that is named, not only in this world, but also in that which is to come:"],
["22", "Ephesians 1:22", "And hath put all things under his feet, and gave him to be the head over all things to the church,"],
["23", "Ephesians 1:23", "Which is his body, the fulness of him that filleth all in all."],
["24", "Ephesians 2:1", "And you hath he quickened, who were dead in trespasses and sins;"],
["25", "Ephesians 2:2", "Wherein in time past ye walked according to the course of this world, according to the prince of the power of the air, the spirit that now worketh in the children of disobedience:"],
["26", "Ephesians 2:3", "Among whom also we all had our conversation in times past in the lusts of our flesh, fulfilling the desires of the flesh and of the mind; and were by nature the children of wrath, even as others."],
["27", "Ephesians 2:4", "But God, who is rich in mercy, for his great love wherewith he loved us,"],
["28", "Ephesians 2:5", "Even when we were dead in sins, hath quickened us together with Christ, (by grace ye are saved;)"],
["29", "Ephesians 2:6", "And hath raised us up together, and made us sit together in heavenly places in Christ Jesus:"],
["30", "Ephesians 2:7", "That in the ages to come he might show the exceeding riches of his grace in his kindness toward us through Christ Jesus."],
["31", "Ephesians 2:8", "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:"],
["32", "Ephesians 2:9", "Not of works, lest any man should boast."],
["33", "Ephesians 2:10", "For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them."],
["34", "Ephesians 2:11", "Wherefore remember, that ye being in time past Gentiles in the flesh, who are called Uncircumcision by that which is called the Circumcision in the flesh made by hands;"],
["35", "Ephesians 2:12", "That at that time ye were without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world:"],
["36", "Ephesians 2:13", "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ."],
["37", "Ephesians 2:14", "For he is our peace, who hath made both one, and hath broken down the middle wall of partition between us;"],
["38", "Ephesians 2:15", "Having abolished in his flesh the enmity, even the law of commandments contained in ordinances; for to make in himself of twain one new man, so making peace;"],
["39", "Ephesians 2:16", "And that he might reconcile both unto God in one body by the cross, having slain the enmity thereby:"],
["40", "Ephesians 2:17", "And came and preached peace to you which were afar off, and to them that were nigh."],
["41", "Ephesians 2:18", "For through him we both have access by one Spirit unto the Father."],
["42", "Ephesians 2:19", "Now therefore ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God;"],
["43", "Ephesians 2:20", "And are built upon the foundation of the apostles and prophets, Jesus Christ himself being the chief corner stone;"],
["44", "Ephesians 2:21", "In whom all the building fitly framed together groweth unto an holy temple in the Lord:"],
["45", "Ephesians 2:22", "In whom ye also are builded together for an habitation of God through the Spirit."],
["46", "Ephesians 3:1", "For this cause I Paul, the prisoner of Jesus Christ for you Gentiles,"],
["47", "Ephesians 3:2", "If ye have heard of the dispensation of the grace of God which is given me to you-ward:"],
["48", "Ephesians 3:3", "How that by revelation he made known unto me the mystery; (as I wrote afore in few words,"],
["49", "Ephesians 3:4", "Whereby, when ye read, ye may understand my knowledge in the mystery of Christ)"],
["50", "Ephesians 3:5", "Which in other ages was not made known unto the sons of men, as it is now revealed unto his holy apostles and prophets by the Spirit;"],
["51", "Ephesians 3:6", "That the Gentiles should be fellowheirs, and of the same body, and partakers of his promise in Christ by the gospel:"],
["52", "Ephesians 3:7", "Whereof I was made a minister, according to the gift of the grace of God given unto me by the effectual working of his power."],
["53", "Ephesians 3:8", "Unto me, who am less than the least of all saints, is this grace given, that I should preach among the Gentiles the unsearchable riches of Christ;"],
["54", "Ephesians 3:9", "And to make all men see what is the fellowship of the mystery, which from the beginning of the world hath been hid in God, who created all things by Jesus Christ:"],
["55", "Ephesians 3:10", "To the intent that now unto the principalities and powers in heavenly places might be known by the church the manifold wisdom of God,"],
["56", "Ephesians 3:11", "According to the eternal purpose which he purposed in Christ Jesus our Lord:"],
["57", "Ephesians 3:12", "In whom we have boldness and access with confidence by the faith of him."],
["58", "Ephesians 3:13", "Wherefore I desire that ye faint not at my tribulations for you, which is your glory."],
["59", "Ephesians 3:14", "For this cause I bow my knees unto the Father of our Lord Jesus Christ,"],
["60", "Ephesians 3:15", "Of whom the whole family in heaven and earth is named,"],
["61", "Ephesians 3:16", "That he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit in the inner man;"],
["62", "Ephesians 3:17", "That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love,"],
["63", "Ephesians 3:18", "May be able to comprehend with all saints what is the breadth, and length, and depth, and height;"],
["64", "Ephesians 3:19", "And to know the love of Christ, which passeth knowledge, that ye might be filled with all the fulness of God."],
["65", "Ephesians 3:20", "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us,"],
["66", "Ephesians 3:21", "Unto him be glory in the church by Christ Jesus throughout all ages, world without end. Amen."],
["67", "Ephesians 4:1", "I therefore, the prisoner of the Lord, beseech you that ye walk worthy of the vocation wherewith ye are called,"],
["68", "Ephesians 4:2", "With all lowliness and meekness, with longsuffering, forbearing one another in love;"],
["69", "Ephesians 4:3", "Endeavouring to keep the unity of the Spirit in the bond of peace."],
["70", "Ephesians 4:4", "There is one body, and one Spirit, even as ye are called in one hope of your calling;"],
["71", "Ephesians 4:5", "One Lord, one faith, one baptism,"],
["72", "Ephesians 4:6", "One God and Father of all, who is above all, and through all, and in you all."],
["73", "Ephesians 4:7", "But unto every one of us is given grace according to the measure of the gift of Christ."],
["74", "Ephesians 4:8", "Wherefore he saith, When he ascended up on high, he led captivity captive, and gave gifts unto men."],
["75", "Ephesians 4:9", "(Now that he ascended, what is it but that he also descended first into the lower parts of the earth?"],
["76", "Ephesians 4:10", "He that descended is the same also that ascended up far above all heavens, that he might fill all things.)"],
["77", "Ephesians 4:11", "And he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers;"],
["78", "Ephesians 4:12", "For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ:"],
["79", "Ephesians 4:13", "Till we all come in the unity of the faith, and of the knowledge of the Son of God, unto a perfect man, unto the measure of the stature of the fulness of Christ:"],
["80", "Ephesians 4:14", "That we henceforth be no more children, tossed to and fro, and carried about with every wind of doctrine, by the sleight of men, and cunning craftiness, whereby they lie in wait to deceive;"],
["81", "Ephesians 4:15", "But speaking the truth in love, may grow up into him in all things, which is the head, even Christ:"],
["82", "Ephesians 4:16", "From whom the whole body fitly joined together and compacted by that which every joint supplieth, according to the effectual working in the measure of every part, maketh increase of the body unto the edifying of itself in love."],
["83", "Ephesians 4:17", "This I say therefore, and testify in the Lord, that ye henceforth walk not as other Gentiles walk, in the vanity of their mind,"],
["84", "Ephesians 4:18", "Having the understanding darkened, being alienated from the life of God through the ignorance that is in them, because of the blindness of their heart:"],
["85", "Ephesians 4:19", "Who being past feeling have given themselves over unto lasciviousness, to work all uncleanness with greediness."],
["86", "Ephesians 4:20", "But ye have not so learned Christ;"],
["87", "Ephesians 4:21", "If so be that ye have heard him, and have been taught by him, as the truth is in Jesus:"],
["88", "Ephesians 4:22", "That ye put off concerning the former conversation the old man, which is corrupt according to the deceitful lusts;"],
["89", "Ephesians 4:23", "And be renewed in the spirit of your mind;"],
["90", "Ephesians 4:24", "And that ye put on the new man, which after God is created in righteousness and true holiness."],
["91", "Ephesians 4:25", "Wherefore putting away lying, speak every man truth with his neighbour: for we are members one of another."],
["92", "Ephesians 4:26", "Be ye angry, and sin not: let not the sun go down upon your wrath:"],
["93", "Ephesians 4:27", "Neither give place to the devil."],
["94", "Ephesians 4:28", "Let him that stole steal no more: but rather let him labour, working with his hands the thing which is good, that he may have to give to him that needeth."],
["95", "Ephesians 4:29", "Let no corrupt communication proceed out of your mouth, but that which is good to the use of edifying, that it may minister grace unto the hearers."],
["96", "Ephesians 4:30", "And grieve not the holy Spirit of God, whereby ye are sealed unto the day of redemption."],
["97", "Ephesians 4:31", "Let all bitterness, and wrath, and anger, and clamour, and evil speaking, be put away from you, with all malice:"],
["98", "Ephesians 4:32", "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you."],
["99", "Ephesians 5:1", "Be ye therefore followers of God, as dear children;"],
["100", "Ephesians 5:2", "And walk in love, as Christ also hath loved us, and hath given himself for us an offering and a sacrifice to God for a sweetsmelling savour."],
["101", "Ephesians 5:3", "But fornication, and all uncleanness, or covetousness, let it not be once named among you, as becometh saints;"],
["102", "Ephesians 5:4", "Neither filthiness, nor foolish talking, nor jesting, which are not convenient: but rather giving of thanks."],
["103", "Ephesians 5:5", "For this ye know, that no whoremonger, nor unclean person, nor covetous man, who is an idolater, hath any inheritance in the kingdom of Christ and of God."],
["104", "Ephesians 5:6", "Let no man deceive you with vain words: for because of these things cometh the wrath of God upon the children of disobedience."],
["105", "Ephesians 5:7", "Be not ye therefore partakers with them."],
["106", "Ephesians 5:8", "For ye were sometimes darkness, but now are ye light in the Lord: walk as children of light:"],
["107", "Ephesians 5:9", "(For the fruit of the Spirit is in all goodness and righteousness and truth;)"],
["108", "Ephesians 5:10", "Proving what is acceptable unto the Lord."],
["109", "Ephesians 5:11", "And have no fellowship with the unfruitful works of darkness, but rather reprove them."],
["110", "Ephesians 5:12", "For it is a shame even to speak of those things which are done of them in secret."],
["111", "Ephesians 5:13", "But all things that are reproved are made manifest by the light: for whatsoever doth make manifest is light."],
["112", "Ephesians 5:14", "Wherefore he saith, Awake thou that sleepest, and arise from the dead, and Christ shall give thee light."],
["113", "Ephesians 5:15", "See then that ye walk circumspectly, not as fools, but as wise,"],
["114", "Ephesians 5:16", "Redeeming the time, because the days are evil."],
["115", "Ephesians 5:17", "Wherefore be ye not unwise, but understanding what the will of the Lord is."],
["116", "Ephesians 5:18", "And be not drunk with wine, wherein is excess; but be filled with the Spirit;"],
["117", "Ephesians 5:19", "Speaking to yourselves in psalms and hymns and spiritual songs, singing and making melody in your heart to the Lord;"],
["118", "Ephesians 5:20", "Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ;"],
["119", "Ephesians 5:21", "Submitting yourselves one to another in the fear of God."],
["120", "Ephesians 5:22", "Wives, submit yourselves unto your own husbands, as unto the Lord."],
["121", "Ephesians 5:23", "For the husband is the head of the wife, even as Christ is the head of the church: and he is the saviour of the body."],
["122", "Ephesians 5:24", "Therefore as the church is subject unto Christ, so let the wives be to their own husbands in every thing."],
["123", "Ephesians 5:25", "Husbands, love your wives, even as Christ also loved the church, and gave himself for it;"],
["124", "Ephesians 5:26", "That he might sanctify and cleanse it with the washing of water by the word,"],
["125", "Ephesians 5:27", "That he might present it to himself a glorious church, not having spot, or wrinkle, or any such thing; but that it should be holy and without blemish."],
["126", "Ephesians 5:28", "So ought men to love their wives as their own bodies. He that loveth his wife loveth himself."],
["127", "Ephesians 5:29", "For no man ever yet hated his own flesh; but nourisheth and cherisheth it, even as the Lord the church:"],
["128", "Ephesians 5:30", "For we are members of his body, of his flesh, and of his bones."],
["129", "Ephesians 5:31", "For this cause shall a man leave his father and mother, and shall be joined unto his wife, and they two shall be one flesh."],
["130", "Ephesians 5:32", "This is a great mystery: but I speak concerning Christ and the church."],
["131", "Ephesians 5:33", "Nevertheless let every one of you in particular so love his wife even as himself; and the wife see that she reverence her husband."],
["132", "Ephesians 6:1", "Children, obey your parents in the Lord: for this is right."],
["133", "Ephesians 6:2", "Honour thy father and mother; which is the first commandment with promise;"],
["134", "Ephesians 6:3", "That it may be well with thee, and thou mayest live long on the earth."],
["135", "Ephesians 6:4", "And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord."],
["136", "Ephesians 6:5", "Servants, be obedient to them that are your masters according to the flesh, with fear and trembling, in singleness of your heart, as unto Christ;"],
["137", "Ephesians 6:6", "Not with eyeservice, as menpleasers; but as the servants of Christ, doing the will of God from the heart;"],
["138", "Ephesians 6:7", "With good will doing service, as to the Lord, and not to men:"],
["139", "Ephesians 6:8", "Knowing that whatsoever good thing any man doeth, the same shall he receive of the Lord, whether he be bond or free."],
["140", "Ephesians 6:9", "And, ye masters, do the same things unto them, forbearing threatening: knowing that your Master also is in heaven; neither is there respect of persons with him."],
["141", "Ephesians 6:10", "Finally, my brethren, be strong in the Lord, and in the power of his might."],
["142", "Ephesians 6:11", "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil."],
["143", "Ephesians 6:12", "For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places."],
["144", "Ephesians 6:13", "Wherefore take unto you the whole armour of God, that ye may be able to withstand in the evil day, and having done all, to stand."],
["145", "Ephesians 6:14", "Stand therefore, having your loins girt about with truth, and having on the breastplate of righteousness;"],
["146", "Ephesians 6:15", "And your feet shod with the preparation of the gospel of peace;"],
["147", "Ephesians 6:16", "Above all, taking the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked."],
["148", "Ephesians 6:17", "And take the helmet of salvation, and the sword of the Spirit, which is the word of God:"],
["149", "Ephesians 6:18", "Praying always with all prayer and supplication in the Spirit, and watching thereunto with all perseverance and supplication for all saints;"],
["150", "Ephesians 6:19", "And for me, that utterance may be given unto me, that I may open my mouth boldly, to make known the mystery of the gospel,"],
["151", "Ephesians 6:20", "For which I am an ambassador in bonds: that therein I may speak boldly, as I ought to speak."],
["152", "Ephesians 6:21", "But that ye also may know my affairs, and how I do, Tychicus, a beloved brother and faithful minister in the Lord, shall make known to you all things:"],
["153", "Ephesians 6:22", "Whom I have sent unto you for the same purpose, that ye might know our affairs, and that he might comfort your hearts."],
["154", "Ephesians 6:23", "Peace be to the brethren, and love with faith, from God the Father and the Lord Jesus Christ."],
["155", "Ephesians 6:24", "Grace be with all them that love our Lord Jesus Christ in sincerity. Amen."],
["156", "Colossians 1:1", "Paul, an apostle of Jesus Christ by the will of God, and Timotheus our brother,"],
["157", "Colossians 1:2", "To the saints and faithful brethren in Christ which are at Colosse: Grace be unto you, and peace, from God our Father and the Lord Jesus Christ."],
["158", "Colossians 1:3", "We give thanks to God and the Father of our Lord Jesus Christ, praying always for you,"],
["159", "Colossians 1:4", "Since we heard of your faith in Christ Jesus, and of the love which ye have to all the saints,"],
["160", "Colossians 1:5", "For the hope which is laid up for you in heaven, whereof ye heard before in the word of the truth of the gospel;"],
["161", "Colossians 1:6", "Which is come unto you, as it is in all the world; and bringeth forth fruit, as it doth also in you, since the day ye heard of it, and knew the grace of God in truth:"],
["162", "Colossians 1:7", "As ye also learned of Epaphras our dear fellowservant, who is for you a faithful minister of Christ;"],
["163", "Colossians 1:8", "Who also declared unto us your love in the Spirit."],
["164", "Colossians 1:9", "For this cause we also, since the day we heard it, do not cease to pray for you, and to desire that ye might be filled with the knowledge of his will in all wisdom and spiritual understanding;"],
["165", "Colossians 1:10", "That ye might walk worthy of the Lord unto all pleasing, being fruitful in every good work, and increasing in the knowledge of God;"],
["166", "Colossians 1:11", "Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness;"],
["167", "Colossians 1:12", "Giving thanks unto the Father, which hath made us meet to be partakers of the inheritance of the saints in light:"],
["168", "Colossians 1:13", "Who hath delivered us from the power of darkness, and hath translated us into the kingdom of his dear Son:"],
["169", "Colossians 1:14", "In whom we have redemption through his blood, even the forgiveness of sins:"],
["170", "Colossians 1:15", "Who is the image of the invisible God, the firstborn of every creature:"],
["171", "Colossians 1:16", "For by him were all things created, that are in heaven, and that are in earth, visible and invisible, whether they be thrones, or dominions, or principalities, or powers: all things were created by him, and for him:"],
["172", "Colossians 1:17", "And he is before all things, and by him all things consist."],
["173", "Colossians 1:18", "And he is the head of the body, the church: who is the beginning, the firstborn from the dead; that in all things he might have the preeminence."],
["174", "Colossians 1:19", "For it pleased the Father that in him should all fulness dwell;"],
["175", "Colossians 1:20", "And, having made peace through the blood of his cross, by him to reconcile all things unto himself; by him, I say, whether they be things in earth, or things in heaven."],
["176", "Colossians 1:21", "And you, that were sometime alienated and enemies in your mind by wicked works, yet now hath he reconciled"],
["177", "Colossians 1:22", "In the body of his flesh through death, to present you holy and unblameable and unreproveable in his sight:"],
["178", "Colossians 1:23", "If ye continue in the faith grounded and settled, and be not moved away from the hope of the gospel, which ye have heard, and which was preached to every creature which is under heaven; whereof I Paul am made a minister;"],
["179", "Colossians 1:24", "Who now rejoice in my sufferings for you, and fill up that which is behind of the afflictions of Christ in my flesh for his body's sake, which is the church:"],
["180", "Colossians 1:25", "Whereof I am made a minister, according to the dispensation of God which is given to me for you, to fulfil the word of God;"],
["181", "Colossians 1:26", "Even the mystery which hath been hid from ages and from generations, but now is made manifest to his saints:"],
["182", "Colossians 1:27", "To whom God would make known what is the riches of the glory of this mystery among the Gentiles; which is Christ in you, the hope of glory:"],
["183", "Colossians 1:28", "Whom we preach, warning every man, and teaching every man in all wisdom; that we may present every man perfect in Christ Jesus:"],
["184", "Colossians 1:29", "Whereunto I also labour, striving according to his working, which worketh in me mightily."],
["185", "Colossians 2:1", "For I would that ye knew what great conflict I have for you, and for them at Laodicea, and for as many as have not seen my face in the flesh;"],
["186", "Colossians 2:2", "That their hearts might be comforted, being knit together in love, and unto all riches of the full assurance of understanding, to the acknowledgement of the mystery of God, and of the Father, and of Christ;"],
["187", "Colossians 2:3", "In whom are hid all the treasures of wisdom and knowledge."],
["188", "Colossians 2:4", "And this I say, lest any man should beguile you with enticing words."],
["189", "Colossians 2:5", "For though I be absent in the flesh, yet am I with you in the spirit, joying and beholding your order, and the stedfastness of your faith in Christ."],
["190", "Colossians 2:6", "As ye have therefore received Christ Jesus the Lord, so walk ye in him:"],
["191", "Colossians 2:7", "Rooted and built up in him, and stablished in the faith, as ye have been taught, abounding therein with thanksgiving."],
["192", "Colossians 2:8", "Beware lest any man spoil you through philosophy and vain deceit, after the tradition of men, after the rudiments of the world, and not after Christ."],
["193", "Colossians 2:9", "For in him dwelleth all the fulness of the Godhead bodily."],
["194", "Colossians 2:10", "And ye are complete in him, which is the head of all principality and power:"],
["195", "Colossians 2:11", "In whom also ye are circumcised with the circumcision made without hands, in putting off the body of the sins of the flesh by the circumcision of Christ:"],
["196", "Colossians 2:12", "Buried with him in baptism, wherein also ye are risen with him through the faith of the operation of God, who hath raised him from the dead."],
["197", "Colossians 2:13", "And you, being dead in your sins and the uncircumcision of your flesh, hath he quickened together with him, having forgiven you all trespasses;"],
["198", "Colossians 2:14", "Blotting out the handwriting of ordinances that was against us, which was contrary to us, and took it out of the way, nailing it to his cross;"],
["199", "Colossians 2:15", "And having spoiled principalities and powers, he made a show of them openly, triumphing over them in it."],
["200", "Colossians 2:16", "Let no man therefore judge you in meat, or in drink, or in respect of an holyday, or of the new moon, or of the sabbath days:"],
["201", "Colossians 2:17", "Which are a shadow of things to come; but the body is of Christ."],
["202", "Colossians 2:18", "Let no man beguile you of your reward in a voluntary humility and worshipping of angels, intruding into those things which he hath not seen, vainly puffed up by his fleshly mind,"],
["203", "Colossians 2:19", "And not holding the Head, from which all the body by joints and bands having nourishment ministered, and knit together, increaseth with the increase of God."],
["204", "Colossians 2:20", "Wherefore if ye be dead with Christ from the rudiments of the world, why, as though living in the world, are ye subject to ordinances,"],
["205", "Colossians 2:21", "(Touch not; taste not; handle not;"],
["206", "Colossians 2:22", "Which all are to perish with the using;) after the commandments and doctrines of men?"],
["207", "Colossians 2:23", "Which things have indeed a show of wisdom in will worship, and humility, and neglecting of the body; not in any honour to the satisfying of the flesh."],
["208", "Colossians 3:1", "If ye then be risen with Christ, seek those things which are above, where Christ sitteth on the right hand of God."],
["209", "Colossians 3:2", "Set your affection on things above, not on things on the earth."],
["210", "Colossians 3:3", "For ye are dead, and your life is hid with Christ in God."],
["211", "Colossians 3:4", "When Christ, who is our life, shall appear, then shall ye also appear with him in glory."],
["212", "Colossians 3:5", "Mortify therefore your members which are upon the earth; fornication, uncleanness, inordinate affection, evil concupiscence, and covetousness, which is idolatry:"],
["213", "Colossians 3:6", "For which things' sake the wrath of God cometh on the children of disobedience:"],
["214", "Colossians 3:7", "In the which ye also walked some time, when ye lived in them."],
["215", "Colossians 3:8", "But now ye also put off all these; anger, wrath, malice, blasphemy, filthy communication out of your mouth."],
["216", "Colossians 3:9", "Lie not one to another, seeing that ye have put off the old man with his deeds;"],
["217", "Colossians 3:10", "And have put on the new man, which is renewed in knowledge after the image of him that created him:"],
["218", "Colossians 3:11", "Where there is neither Greek nor Jew, circumcision nor uncircumcision, Barbarian, Scythian, bond nor free: but Christ is all, and in all."],
["219", "Colossians 3:12", "Put on therefore, as the elect of God, holy and beloved, bowels of mercies, kindness, humbleness of mind, meekness, longsuffering;"],
["220", "Colossians 3:13", "Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye."],
["221", "Colossians 3:14", "And above all these things put on charity, which is the bond of perfectness."],
["222", "Colossians 3:15", "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful."],
["223", "Colossians 3:16", "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord."],
["224", "Colossians 3:17", "And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him."],
["225", "Colossians 3:18", "Wives, submit yourselves unto your own husbands, as it is fit in the Lord."],
["226", "Colossians 3:19", "Husbands, love your wives, and be not bitter against them."],
["227", "Colossians 3:20", "Children, obey your parents in all things: for this is well pleasing unto the Lord."],
["228", "Colossians 3:21", "Fathers, provoke not your children to anger, lest they be discouraged."],
["229", "Colossians 3:22", "Servants, obey in all things your masters according to the flesh; not with eyeservice, as menpleasers; but in singleness of heart, fearing God:"],
["230", "Colossians 3:23", "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;"],
["231", "Colossians 3:24", "Knowing that of the Lord ye shall receive the reward of the inheritance: for ye serve the Lord Christ."],
["232", "Colossians 3:25", "But he that doeth wrong shall receive for the wrong which he hath done: and there is no respect of persons."],
["233", "Colossians 4:1", "Masters, give unto your servants that which is just and equal; knowing that ye also have a Master in heaven."],
["234", "Colossians 4:2", "Continue in prayer, and watch in the same with thanksgiving;"],
["235", "Colossians 4:3", "Withal praying also for us, that God would open unto us a door of utterance, to speak the mystery of Christ, for which I am also in bonds:"],
["236", "Colossians 4:4", "That I may make it manifest, as I ought to speak."],
["237", "Colossians 4:5", "Walk in wisdom toward them that are without, redeeming the time."],
["238", "Colossians 4:6", "Let your speech be alway with grace, seasoned with salt, that ye may know how ye ought to answer every man."],
["239", "Colossians 4:7", "All my state shall Tychicus declare unto you, who is a beloved brother, and a faithful minister and fellowservant in the Lord:"],
["240", "Colossians 4:8", "Whom I have sent unto you for the same purpose, that he might know your estate, and comfort your hearts;"],
["241", "Colossians 4:9", "With Onesimus, a faithful and beloved brother, who is one of you. They shall make known unto you all things which are done here."],
["242", "Colossians 4:10", "Aristarchus my fellowprisoner saluteth you, and Marcus, sister's son to Barnabas, (touching whom ye received commandments: if he come unto you, receive him;)"],
["243", "Colossians 4:11", "And Jesus, which is called Justus, who are of the circumcision. These only are my fellowworkers unto the kingdom of God, which have been a comfort unto me."],
["244", "Colossians 4:12", "Epaphras, who is one of you, a servant of Christ, saluteth you, always labouring fervently for you in prayers, that ye may stand perfect and complete in all the will of God."],
["245", "Colossians 4:13", "For I bear him record, that he hath a great zeal for you, and them that are in Laodicea, and them in Hierapolis."],
["246", "Colossians 4:14", "Luke, the beloved physician, and Demas, greet you."],
["247", "Colossians 4:15", "Salute the brethren which are in Laodicea, and Nymphas, and the church which is in his house."],
["248", "Colossians 4:16", "And when this epistle is read among you, cause that it be read also in the church of the Laodiceans; and that ye likewise read the epistle from Laodicea."],
["249", "Colossians 4:17", "And say to Archippus, Take heed to the ministry which thou hast received in the Lord, that thou fulfil it."],
["250", "Colossians 4:18", "The salutation by the hand of me Paul. Remember my bonds. Grace be with you. Amen."],
["251", "Philemon 1:1", "Paul, a prisoner of Jesus Christ, and Timothy our brother, unto Philemon our dearly beloved, and fellowlabourer,"],
["252", "Philemon 1:2", "And to our beloved Apphia, and Archippus our fellowsoldier, and to the church in thy house:"],
["253", "Philemon 1:3", "Grace to you, and peace, from God our Father and the Lord Jesus Christ."],
["254", "Philemon 1:4", "I thank my God, making mention of thee always in my prayers,"],
["255", "Philemon 1:5", "Hearing of thy love and faith, which thou hast toward the Lord Jesus, and toward all saints;"],
["256", "Philemon 1:6", "That the communication of thy faith may become effectual by the acknowledging of every good thing which is in you in Christ Jesus."],
["257", "Philemon 1:7", "For we have great joy and consolation in thy love, because the bowels of the saints are refreshed by thee, brother."],
["258", "Philemon 1:8", "Wherefore, though I might be much bold in Christ to enjoin thee that which is convenient,"],
["259", "Philemon 1:9", "Yet for love's sake I rather beseech thee, being such an one as Paul the aged, and now also a prisoner of Jesus Christ."],
["260", "Philemon 1:10", "I beseech thee for my son Onesimus, whom I have begotten in my bonds:"],
["261", "Philemon 1:11", "Which in time past was to thee unprofitable, but now profitable to thee and to me:"],
["262", "Philemon 1:12", "Whom I have sent again: thou therefore receive him, that is, mine own bowels:"],
["263", "Philemon 1:13", "Whom I would have retained with me, that in thy stead he might have ministered unto me in the bonds of the gospel:"],
["264", "Philemon 1:14", "But without thy mind would I do nothing; that thy benefit should not be as it were of necessity, but willingly."],
["265", "Philemon 1:15", "For perhaps he therefore departed for a season, that thou shouldest receive him for ever;"],
["266", "Philemon 1:16", "Not now as a servant, but above a servant, a brother beloved, specially to me, but how much more unto thee, both in the flesh, and in the Lord?"],
["267", "Philemon 1:17", "If thou count me therefore a partner, receive him as myself."],
["268", "Philemon 1:18", "If he hath wronged thee, or oweth thee ought, put that on mine account;"],
["269", "Philemon 1:19", "I Paul have written it with mine own hand, I will repay it: albeit I do not say to thee how thou owest unto me even thine own self besides."],
["270", "Philemon 1:20", "Yea, brother, let me have joy of thee in the Lord: refresh my bowels in the Lord."],
["271", "Philemon 1:21", "Having confidence in thy obedience I wrote unto thee, knowing that thou wilt also do more than I say."],
["272", "Philemon 1:22", "But withal prepare me also a lodging: for I trust that through your prayers I shall be given unto you."],
["273", "Philemon 1:23", "There salute thee Epaphras, my fellowprisoner in Christ Jesus;"],
["274", "Philemon 1:24", "Marcus, Aristarchus, Demas, Lucas, my fellowlabourers."],
["275", "Philemon 1:25", "The grace of our Lord Jesus Christ be with your spirit. Amen."],
["276", "1 Timothy 1:1", "Paul, an apostle of Jesus Christ by the commandment of God our Saviour, and Lord Jesus Christ, which is our hope;"],
["277", "1 Timothy 1:2", "Unto Timothy, my own son in the faith: Grace, mercy, and peace, from God our Father and Jesus Christ our Lord."],
["278", "1 Timothy 1:3", "As I besought thee to abide still at Ephesus, when I went into Macedonia, that thou mightest charge some that they teach no other doctrine,"],
["279", "1 Timothy 1:4", "Neither give heed to fables and endless genealogies, which minister questions, rather than godly edifying which is in faith: so do."],
["280", "1 Timothy 1:5", "Now the end of the commandment is charity out of a pure heart, and of a good conscience, and of faith unfeigned:"],
["281", "1 Timothy 1:6", "From which some having swerved have turned aside unto vain jangling;"],
["282", "1 Timothy 1:7", "Desiring to be teachers of the law; understanding neither what they say, nor whereof they affirm."],
["283", "1 Timothy 1:8", "But we know that the law is good, if a man use it lawfully;"],
["284", "1 Timothy 1:9", "Knowing this, that the law is not made for a righteous man, but for the lawless and disobedient, for the ungodly and for sinners, for unholy and profane, for murderers of fathers and murderers of mothers, for manslayers,"],
["285", "1 Timothy 1:10", "For whoremongers, for them that defile themselves with mankind, for menstealers, for liars, for perjured persons, and if there be any other thing that is contrary to sound doctrine;"],
["286", "1 Timothy 1:11", "According to the glorious gospel of the blessed God, which was committed to my trust."],
["287", "1 Timothy 1:12", "And I thank Christ Jesus our Lord, who hath enabled me, for that he counted me faithful, putting me into the ministry;"],
["288", "1 Timothy 1:13", "Who was before a blasphemer, and a persecutor, and injurious: but I obtained mercy, because I did it ignorantly in unbelief."],
["289", "1 Timothy 1:14", "And the grace of our Lord was exceeding abundant with faith and love which is in Christ Jesus."],
["290", "1 Timothy 1:15", "This is a faithful saying, and worthy of all acceptation, that Christ Jesus came into the world to save sinners; of whom I am chief."],
["291", "1 Timothy 1:16", "Howbeit for this cause I obtained mercy, that in me first Jesus Christ might show forth all longsuffering, for a pattern to them which should hereafter believe on him to life everlasting."],
["292", "1 Timothy 1:17", "Now unto the King eternal, immortal, invisible, the only wise God, be honour and glory for ever and ever. Amen."],
["293", "1 Timothy 1:18", "This charge I commit unto thee, son Timothy, according to the prophecies which went before on thee, that thou by them mightest war a good warfare;"],
["294", "1 Timothy 1:19", "Holding faith, and a good conscience; which some having put away concerning faith have made shipwreck:"],
["295", "1 Timothy 1:20", "Of whom is Hymenaeus and Alexander; whom I have delivered unto Satan, that they may learn not to blaspheme."],
["296", "1 Timothy 2:1", "I exhort therefore, that, first of all, supplications, prayers, intercessions, and giving of thanks, be made for all men;"],
["297", "1 Timothy 2:2", "For kings, and for all that are in authority; that we may lead a quiet and peaceable life in all godliness and honesty."],
["298", "1 Timothy 2:3", "For this is good and acceptable in the sight of God our Saviour;"],
["299", "1 Timothy 2:4", "Who will have all men to be saved, and to come unto the knowledge of the truth."],
["300", "1 Timothy 2:5", "For there is one God, and one mediator between God and men, the man Christ Jesus;"],
["301", "1 Timothy 2:6", "Who gave himself a ransom for all, to be testified in due time."],
["302", "1 Timothy 2:7", "Whereunto I am ordained a preacher, and an apostle, (I speak the truth in Christ, and lie not;) a teacher of the Gentiles in faith and verity."],
["303", "1 Timothy 2:8", "I will therefore that men pray every where, lifting up holy hands, without wrath and doubting."],
["304", "1 Timothy 2:9", "In like manner also, that women adorn themselves in modest apparel, with shamefacedness and sobriety; not with broided hair, or gold, or pearls, or costly array;"],
["305", "1 Timothy 2:10", "But (which becometh women professing godliness) with good works."],
["306", "1 Timothy 2:11", "Let the woman learn in silence with all subjection."],
["307", "1 Timothy 2:12", "But I suffer not a woman to teach, nor to usurp authority over the man, but to be in silence."],
["308", "1 Timothy 2:13", "For Adam was first formed, then Eve."],
["309", "1 Timothy 2:14", "And Adam was not deceived, but the woman being deceived was in the transgression."],
["310", "1 Timothy 2:15", "Notwithstanding she shall be saved in childbearing, if they continue in faith and charity and holiness with sobriety."],
["311", "1 Timothy 3:1", "This is a true saying, If a man desire the office of a bishop, he desireth a good work."],
["312", "1 Timothy 3:2", "A bishop then must be blameless, the husband of one wife, vigilant, sober, of good behaviour, given to hospitality, apt to teach;"],
["313", "1 Timothy 3:3", "Not given to wine, no striker, not greedy of filthy lucre; but patient, not a brawler, not covetous;"],
["314", "1 Timothy 3:4", "One that ruleth well his own house, having his children in subjection with all gravity;"],
["315", "1 Timothy 3:5", "(For if a man know not how to rule his own house, how shall he take care of the church of God?)"],
["316", "1 Timothy 3:6", "Not a novice, lest being lifted up with pride he fall into the condemnation of the devil."],
["317", "1 Timothy 3:7", "Moreover he must have a good report of them which are without; lest he fall into reproach and the snare of the devil."],
["318", "1 Timothy 3:8", "Likewise must the deacons be grave, not doubletongued, not given to much wine, not greedy of filthy lucre;"],
["319", "1 Timothy 3:9", "Holding the mystery of the faith in a pure conscience."],
["320", "1 Timothy 3:10", "And let these also first be proved; then let them use the office of a deacon, being found blameless."],
["321", "1 Timothy 3:11", "Even so must their wives be grave, not slanderers, sober, faithful in all things."],
["322", "1 Timothy 3:12", "Let the deacons be the husbands of one wife, ruling their children and their own houses well."],
["323", "1 Timothy 3:13", "For they that have used the office of a deacon well purchase to themselves a good degree, and great boldness in the faith which is in Christ Jesus."],
["324", "1 Timothy 3:14", "These things write I unto thee, hoping to come unto thee shortly:"],
["325", "1 Timothy 3:15", "But if I tarry long, that thou mayest know how thou oughtest to behave thyself in the house of God, which is the church of the living God, the pillar and ground of the truth."],
["326", "1 Timothy 3:16", "And without controversy great is the mystery of godliness: God was manifest in the flesh, justified in the Spirit, seen of angels, preached unto the Gentiles, believed on in the world, received up into glory."],
["327", "1 Timothy 4:1", "Now the Spirit speaketh expressly, that in the latter times some shall depart from the faith, giving heed to seducing spirits, and doctrines of devils;"],
["328", "1 Timothy 4:2", "Speaking lies in hypocrisy; having their conscience seared with a hot iron;"],
["329", "1 Timothy 4:3", "Forbidding to marry, and commanding to abstain from meats, which God hath created to be received with thanksgiving of them which believe and know the truth."],
["330", "1 Timothy 4:4", "For every creature of God is good, and nothing to be refused, if it be received with thanksgiving:"],
["331", "1 Timothy 4:5", "For it is sanctified by the word of God and prayer."],
["332", "1 Timothy 4:6", "If thou put the brethren in remembrance of these things, thou shalt be a good minister of Jesus Christ, nourished up in the words of faith and of good doctrine, whereunto thou hast attained."],
["333", "1 Timothy 4:7", "But refuse profane and old wives' fables, and exercise thyself rather unto godliness."],
["334", "1 Timothy 4:8", "For bodily exercise profiteth little: but godliness is profitable unto all things, having promise of the life that now is, and of that which is to come."],
["335", "1 Timothy 4:9", "This is a faithful saying and worthy of all acceptation."],
["336", "1 Timothy 4:10", "For therefore we both labour and suffer reproach, because we trust in the living God, who is the Saviour of all men, specially of those that believe."],
["337", "1 Timothy 4:11", "These things command and teach."],
["338", "1 Timothy 4:12", "Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity."],
["339", "1 Timothy 4:13", "Till I come, give attendance to reading, to exhortation, to doctrine."],
["340", "1 Timothy 4:14", "Neglect not the gift that is in thee, which was given thee by prophecy, with the laying on of the hands of the presbytery."],
["341", "1 Timothy 4:15", "Meditate upon these things; give thyself wholly to them; that thy profiting may appear to all."],
["342", "1 Timothy 4:16", "Take heed unto thyself, and unto the doctrine; continue in them: for in doing this thou shalt both save thyself, and them that hear thee."],
["343", "1 Timothy 5:1", "Rebuke not an elder, but intreat him as a father; and the younger men as brethren;"],
["344", "1 Timothy 5:2", "The elder women as mothers; the younger as sisters, with all purity."],
["345", "1 Timothy 5:3", "Honour widows that are widows indeed."],
["346", "1 Timothy 5:4", "But if any widow have children or nephews, let them learn first to show piety at home, and to requite their parents: for that is good and acceptable before God."],
["347", "1 Timothy 5:5", "Now she that is a widow indeed, and desolate, trusteth in God, and continueth in supplications and prayers night and day."],
["348", "1 Timothy 5:6", "But she that liveth in pleasure is dead while she liveth."],
["349", "1 Timothy 5:7", "And these things give in charge, that they may be blameless."],
["350", "1 Timothy 5:8", "But if any provide not for his own, and specially for those of his own house, he hath denied the faith, and is worse than an infidel."],
["351", "1 Timothy 5:9", "Let not a widow be taken into the number under threescore years old, having been the wife of one man,"],
["352", "1 Timothy 5:10", "Well reported of for good works; if she have brought up children, if she have lodged strangers, if she have washed the saints' feet, if she have relieved the afflicted, if she have diligently followed every good work."],
["353", "1 Timothy 5:11", "But the younger widows refuse: for when they have begun to wax wanton against Christ, they will marry;"],
["354", "1 Timothy 5:12", "Having damnation, because they have cast off their first faith."],
["355", "1 Timothy 5:13", "And withal they learn to be idle, wandering about from house to house; and not only idle, but tattlers also and busybodies, speaking things which they ought not."],
["356", "1 Timothy 5:14", "I will therefore that the younger women marry, bear children, guide the house, give none occasion to the adversary to speak reproachfully."],
["357", "1 Timothy 5:15", "For some are already turned aside after Satan."],
["358", "1 Timothy 5:16", "If any man or woman that believeth have widows, let them relieve them, and let not the church be charged; that it may relieve them that are widows indeed."],
["359", "1 Timothy 5:17", "Let the elders that rule well be counted worthy of double honour, especially they who labour in the word and doctrine."],
["360", "1 Timothy 5:18", "For the scripture saith, Thou shalt not muzzle the ox that treadeth out the corn. And, The labourer is worthy of his reward."],
["361", "1 Timothy 5:19", "Against an elder receive not an accusation, but before two or three witnesses."],
["362", "1 Timothy 5:20", "Them that sin rebuke before all, that others also may fear."],
["363", "1 Timothy 5:21", "I charge thee before God, and the Lord Jesus Christ, and the elect angels, that thou observe these things without preferring one before another, doing nothing by partiality."],
["364", "1 Timothy 5:22", "Lay hands suddenly on no man, neither be partaker of other men's sins: keep thyself pure."],
["365", "1 Timothy 5:23", "Drink no longer water, but use a little wine for thy stomach's sake and thine often infirmities."],
["366", "1 Timothy 5:24", "Some men's sins are open beforehand, going before to judgment; and some men they follow after."],
["367", "1 Timothy 5:25", "Likewise also the good works of some are manifest beforehand; and they that are otherwise cannot be hid."],
["368", "1 Timothy 6:1", "Let as many servants as are under the yoke count their own masters worthy of all honour, that the name of God and his doctrine be not blasphemed."],
["369", "1 Timothy 6:2", "And they that have believing masters, let them not despise them, because they are brethren; but rather do them service, because they are faithful and beloved, partakers of the benefit. These things teach and exhort."],
["370", "1 Timothy 6:3", "If any man teach otherwise, and consent not to wholesome words, even the words of our Lord Jesus Christ, and to the doctrine which is according to godliness;"],
["371", "1 Timothy 6:4", "He is proud, knowing nothing, but doting about questions and strifes of words, whereof cometh envy, strife, railings, evil surmisings,"],
["372", "1 Timothy 6:5", "Perverse disputings of men of corrupt minds, and destitute of the truth, supposing that gain is godliness: from such withdraw thyself."],
["373", "1 Timothy 6:6", "But godliness with contentment is great gain."],
["374", "1 Timothy 6:7", "For we brought nothing into this world, and it is certain we can carry nothing out."],
["375", "1 Timothy 6:8", "And having food and raiment let us be therewith content."],
["376", "1 Timothy 6:9", "But they that will be rich fall into temptation and a snare, and into many foolish and hurtful lusts, which drown men in destruction and perdition."],
["377", "1 Timothy 6:10", "For the love of money is the root of all evil: which while some coveted after, they have erred from the faith, and pierced themselves through with many sorrows."],
["378", "1 Timothy 6:11", "But thou, O man of God, flee these things; and follow after righteousness, godliness, faith, love, patience, meekness."],
["379", "1 Timothy 6:12", "Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called, and hast professed a good profession before many witnesses."],
["380", "1 Timothy 6:13", "I give thee charge in the sight of God, who quickeneth all things, and before Christ Jesus, who before Pontius Pilate witnessed a good confession;"],
["381", "1 Timothy 6:14", "That thou keep this commandment without spot, unrebukeable, until the appearing of our Lord Jesus Christ:"],
["382", "1 Timothy 6:15", "Which in his times he shall show, who is the blessed and only Potentate, the King of kings, and Lord of lords;"],
["383", "1 Timothy 6:16", "Who only hath immortality, dwelling in the light which no man can approach unto; whom no man hath seen, nor can see: to whom be honour and power everlasting. Amen."],
["384", "1 Timothy 6:17", "Charge them that are rich in this world, that they be not highminded, nor trust in uncertain riches, but in the living God, who giveth us richly all things to enjoy;"],
["385", "1 Timothy 6:18", "That they do good, that they be rich in good works, ready to distribute, willing to communicate;"],
["386", "1 Timothy 6:19", "Laying up in store for themselves a good foundation against the time to come, that they may lay hold on eternal life."],
["387", "1 Timothy 6:20", "O Timothy, keep that which is committed to thy trust, avoiding profane and vain babblings, and oppositions of science falsely so called:"],
["388", "1 Timothy 6:21", "Which some professing have erred concerning the faith. Grace be with thee. Amen."],
["389", "Titus 1:1", "Paul, a servant of God, and an apostle of Jesus Christ, according to the faith of God's elect, and the acknowledging of the truth which is after godliness;"],
["390", "Titus 1:2", "In hope of eternal life, which God, that cannot lie, promised before the world began;"],
["391", "Titus 1:3", "But hath in due times manifested his word through preaching, which is committed unto me according to the commandment of God our Saviour;"],
["392", "Titus 1:4", "To Titus, mine own son after the common faith: Grace, mercy, and peace, from God the Father and the Lord Jesus Christ our Saviour."],
["393", "Titus 1:5", "For this cause left I thee in Crete, that thou shouldest set in order the things that are wanting, and ordain elders in every city, as I had appointed thee:"],
["394", "Titus 1:6", "If any be blameless, the husband of one wife, having faithful children not accused of riot or unruly."],
["395", "Titus 1:7", "For a bishop must be blameless, as the steward of God; not selfwilled, not soon angry, not given to wine, no striker, not given to filthy lucre;"],
["396", "Titus 1:8", "But a lover of hospitality, a lover of good men, sober, just, holy, temperate;"],
["397", "Titus 1:9", "Holding fast the faithful word as he hath been taught, that he may be able by sound doctrine both to exhort and to convince the gainsayers."],
["398", "Titus 1:10", "For there are many unruly and vain talkers and deceivers, specially they of the circumcision:"],
["399", "Titus 1:11", "Whose mouths must be stopped, who subvert whole houses, teaching things which they ought not, for filthy lucre's sake."],
["400", "Titus 1:12", "One of themselves, even a prophet of their own, said, The Cretians are alway liars, evil beasts, slow bellies."],
["401", "Titus 1:13", "This witness is true. Wherefore rebuke them sharply, that they may be sound in the faith;"],
["402", "Titus 1:14", "Not giving heed to Jewish fables, and commandments of men, that turn from the truth."],
["403", "Titus 1:15", "Unto the pure all things are pure: but unto them that are defiled and unbelieving is nothing pure; but even their mind and conscience is defiled."],
["404", "Titus 1:16", "They profess that they know God; but in works they deny him, being abominable, and disobedient, and unto every good work reprobate."],
["405", "Titus 2:1", "But speak thou the things which become sound doctrine:"],
["406", "Titus 2:2", "That the aged men be sober, grave, temperate, sound in faith, in charity, in patience."],
["407", "Titus 2:3", "The aged women likewise, that they be in behaviour as becometh holiness, not false accusers, not given to much wine, teachers of good things;"],
["408", "Titus 2:4", "That they may teach the young women to be sober, to love their husbands, to love their children,"],
["409", "Titus 2:5", "To be discreet, chaste, keepers at home, good, obedient to their own husbands, that the word of God be not blasphemed."],
["410", "Titus 2:6", "Young men likewise exhort to be sober minded."],
["411", "Titus 2:7", "In all things showing thyself a pattern of good works: in doctrine showing uncorruptness, gravity, sincerity,"],
["412", "Titus 2:8", "Sound speech, that cannot be condemned; that he that is of the contrary part may be ashamed, having no evil thing to say of you."],
["413", "Titus 2:9", "Exhort servants to be obedient unto their own masters, and to please them well in all things; not answering again;"],
["414", "Titus 2:10", "Not purloining, but showing all good fidelity; that they may adorn the doctrine of God our Saviour in all things."],
["415", "Titus 2:11", "For the grace of God that bringeth salvation hath appeared to all men,"],
["416", "Titus 2:12", "Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world;"],
["417", "Titus 2:13", "Looking for that blessed hope, and the glorious appearing of the great God and our Saviour Jesus Christ;"],
["418", "Titus 2:14", "Who gave himself for us, that he might redeem us from all iniquity, and purify unto himself a peculiar people, zealous of good works."],
["419", "Titus 2:15", "These things speak, and exhort, and rebuke with all authority. Let no man despise thee."],
["420", "Titus 3:1", "Put them in mind to be subject to principalities and powers, to obey magistrates, to be ready to every good work,"],
["421", "Titus 3:2", "To speak evil of no man, to be no brawlers, but gentle, showing all meekness unto all men."],
["422", "Titus 3:3", "For we ourselves also were sometimes foolish, disobedient, deceived, serving divers lusts and pleasures, living in malice and envy, hateful, and hating one another."],
["423", "Titus 3:4", "But after that the kindness and love of God our Saviour toward man appeared,"],
["424", "Titus 3:5", "Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost;"],
["425", "Titus 3:6", "Which he shed on us abundantly through Jesus Christ our Saviour;"],
["426", "Titus 3:7", "That being justified by his grace, we should be made heirs according to the hope of eternal life."],
["427", "Titus 3:8", "This is a faithful saying, and these things I will that thou affirm constantly, that they which have believed in God might be careful to maintain good works. These things are good and profitable unto men."],
["428", "Titus 3:9", "But avoid foolish questions, and genealogies, and contentions, and strivings about the law; for they are unprofitable and vain."],
["429", "Titus 3:10", "A man that is an heretick after the first and second admonition reject;"],
["430", "Titus 3:11", "Knowing that he that is such is subverted, and sinneth, being condemned of himself."],
["431", "Titus 3:12", "When I shall send Artemas unto thee, or Tychicus, be diligent to come unto me to Nicopolis: for I have determined there to winter."],
["432", "Titus 3:13", "Bring Zenas the lawyer and Apollos on their journey diligently, that nothing be wanting unto them."],
["433", "Titus 3:14", "And let ours also learn to maintain good works for necessary uses, that they be not unfruitful."],
["434", "Titus 3:15", "All that are with me salute thee. Greet them that love us in the faith. Grace be with you all. Amen."],
["435", "2 Timothy 1:1", "Paul, an apostle of Jesus Christ by the will of God, according to the promise of life which is in Christ Jesus,"],
["436", "2 Timothy 1:2", "To Timothy, my dearly beloved son: Grace, mercy, and peace, from God the Father and Christ Jesus our Lord."],
["437", "2 Timothy 1:3", "I thank God, whom I serve from my forefathers with pure conscience, that without ceasing I have remembrance of thee in my prayers night and day;"],
["438", "2 Timothy 1:4", "Greatly desiring to see thee, being mindful of thy tears, that I may be filled with joy;"],
["439", "2 Timothy 1:5", "When I call to remembrance the unfeigned faith that is in thee, which dwelt first in thy grandmother Lois, and thy mother Eunice; and I am persuaded that in thee also."],
["440", "2 Timothy 1:6", "Wherefore I put thee in remembrance that thou stir up the gift of God, which is in thee by the putting on of my hands."],
["441", "2 Timothy 1:7", "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind."],
["442", "2 Timothy 1:8", "Be not thou therefore ashamed of the testimony of our Lord, nor of me his prisoner: but be thou partaker of the afflictions of the gospel according to the power of God;"],
["443", "2 Timothy 1:9", "Who hath saved us, and called us with an holy calling, not according to our works, but according to his own purpose and grace, which was given us in Christ Jesus before the world began,"],
["444", "2 Timothy 1:10", "But is now made manifest by the appearing of our Saviour Jesus Christ, who hath abolished death, and hath brought life and immortality to light through the gospel:"],
["445", "2 Timothy 1:11", "Whereunto I am appointed a preacher, and an apostle, and a teacher of the Gentiles."],
["446", "2 Timothy 1:12", "For the which cause I also suffer these things: nevertheless I am not ashamed: for I know whom I have believed, and am persuaded that he is able to keep that which I have committed unto him against that day."],
["447", "2 Timothy 1:13", "Hold fast the form of sound words, which thou hast heard of me, in faith and love which is in Christ Jesus."],
["448", "2 Timothy 1:14", "That good thing which was committed unto thee keep by the Holy Ghost which dwelleth in us."],
["449", "2 Timothy 1:15", "This thou knowest, that all they which are in Asia be turned away from me; of whom are Phygellus and Hermogenes."],
["450", "2 Timothy 1:16", "The Lord give mercy unto the house of Onesiphorus; for he oft refreshed me, and was not ashamed of my chain:"],
["451", "2 Timothy 1:17", "But, when he was in Rome, he sought me out very diligently, and found me."],
["452", "2 Timothy 1:18", "The Lord grant unto him that he may find mercy of the Lord in that day: and in how many things he ministered unto me at Ephesus, thou knowest very well."],
["453", "2 Timothy 2:1", "Thou therefore, my son, be strong in the grace that is in Christ Jesus."],
["454", "2 Timothy 2:2", "And the things that thou hast heard of me among many witnesses, the same commit thou to faithful men, who shall be able to teach others also."],
["455", "2 Timothy 2:3", "Thou therefore endure hardness, as a good soldier of Jesus Christ."],
["456", "2 Timothy 2:4", "No man that warreth entangleth himself with the affairs of this life; that he may please him who hath chosen him to be a soldier."],
["457", "2 Timothy 2:5", "And if a man also strive for masteries, yet is he not crowned, except he strive lawfully."],
["458", "2 Timothy 2:6", "The husbandman that laboureth must be first partaker of the fruits."],
["459", "2 Timothy 2:7", "Consider what I say; and the Lord give thee understanding in all things."],
["460", "2 Timothy 2:8", "Remember that Jesus Christ of the seed of David was raised from the dead according to my gospel:"],
["461", "2 Timothy 2:9", "Wherein I suffer trouble, as an evil doer, even unto bonds; but the word of God is not bound."],
["462", "2 Timothy 2:10", "Therefore I endure all things for the elect's sakes, that they may also obtain the salvation which is in Christ Jesus with eternal glory."],
["463", "2 Timothy 2:11", "It is a faithful saying: For if we be dead with him, we shall also live with him:"],
["464", "2 Timothy 2:12", "If we suffer, we shall also reign with him: if we deny him, he also will deny us:"],
["465", "2 Timothy 2:13", "If we believe not, yet he abideth faithful: he cannot deny himself."],
["466", "2 Timothy 2:14", "Of these things put them in remembrance, charging them before the Lord that they strive not about words to no profit, but to the subverting of the hearers."],
["467", "2 Timothy 2:15", "Study to show thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth."],
["468", "2 Timothy 2:16", "But shun profane and vain babblings: for they will increase unto more ungodliness."],
["469", "2 Timothy 2:17", "And their word will eat as doth a canker: of whom is Hymenaeus and Philetus;"],
["470", "2 Timothy 2:18", "Who concerning the truth have erred, saying that the resurrection is past already; and overthrow the faith of some."],
["471", "2 Timothy 2:19", "Nevertheless the foundation of God standeth sure, having this seal, The Lord knoweth them that are his. And, Let every one that nameth the name of Christ depart from iniquity."],
["472", "2 Timothy 2:20", "But in a great house there are not only vessels of gold and of silver, but also of wood and of earth; and some to honour, and some to dishonour."],
["473", "2 Timothy 2:21", "If a man therefore purge himself from these, he shall be a vessel unto honour, sanctified, and meet for the master's use, and prepared unto every good work."],
["474", "2 Timothy 2:22", "Flee also youthful lusts: but follow righteousness, faith, charity, peace, with them that call on the Lord out of a pure heart."],
["475", "2 Timothy 2:23", "But foolish and unlearned questions avoid, knowing that they do gender strifes."],
["476", "2 Timothy 2:24", "And the servant of the Lord must not strive; but be gentle unto all men, apt to teach, patient,"],
["477", "2 Timothy 2:25", "In meekness instructing those that oppose themselves; if God peradventure will give them repentance to the acknowledging of the truth;"],
["478", "2 Timothy 2:26", "And that they may recover themselves out of the snare of the devil, who are taken captive by him at his will."],
["479", "2 Timothy 3:1", "This know also, that in the last days perilous times shall come."],
["480", "2 Timothy 3:2", "For men shall be lovers of their own selves, covetous, boasters, proud, blasphemers, disobedient to parents, unthankful, unholy,"],
["481", "2 Timothy 3:3", "Without natural affection, trucebreakers, false accusers, incontinent, fierce, despisers of those that are good,"],
["482", "2 Timothy 3:4", "Traitors, heady, highminded, lovers of pleasures more than lovers of God;"],
["483", "2 Timothy 3:5", "Having a form of godliness, but denying the power thereof: from such turn away."],
["484", "2 Timothy 3:6", "For of this sort are they which creep into houses, and lead captive silly women laden with sins, led away with divers lusts,"],
["485", "2 Timothy 3:7", "Ever learning, and never able to come to the knowledge of the truth."],
["486", "2 Timothy 3:8", "Now as Jannes and Jambres withstood Moses, so do these also resist the truth: men of corrupt minds, reprobate concerning the faith."],
["487", "2 Timothy 3:9", "But they shall proceed no further: for their folly shall be manifest unto all men, as theirs also was."],
["488", "2 Timothy 3:10", "But thou hast fully known my doctrine, manner of life, purpose, faith, longsuffering, charity, patience,"],
["489", "2 Timothy 3:11", "Persecutions, afflictions, which came unto me at Antioch, at Iconium, at Lystra; what persecutions I endured: but out of them all the Lord delivered me."],
["490", "2 Timothy 3:12", "Yea, and all that will live godly in Christ Jesus shall suffer persecution."],
["491", "2 Timothy 3:13", "But evil men and seducers shall wax worse and worse, deceiving, and being deceived."],
["492", "2 Timothy 3:14", "But continue thou in the things which thou hast learned and hast been assured of, knowing of whom thou hast learned them;"],
["493", "2 Timothy 3:15", "And that from a child thou hast known the holy scriptures, which are able to make thee wise unto salvation through faith which is in Christ Jesus."],
["494", "2 Timothy 3:16", "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness:"],
["495", "2 Timothy 3:17", "That the man of God may be perfect, throughly furnished unto all good works."],
["496", "2 Timothy 4:1", "I charge thee therefore before God, and the Lord Jesus Christ, who shall judge the quick and the dead at his appearing and his kingdom;"],
["497", "2 Timothy 4:2", "Preach the word; be instant in season, out of season; reprove, rebuke, exhort with all longsuffering and doctrine."],
["498", "2 Timothy 4:3", "For the time will come when they will not endure sound doctrine; but after their own lusts shall they heap to themselves teachers, having itching ears;"],
["499", "2 Timothy 4:4", "And they shall turn away their ears from the truth, and shall be turned unto fables."],
["500", "2 Timothy 4:5", "But watch thou in all things, endure afflictions, do the work of an evangelist, make full proof of thy ministry."],
["501", "2 Timothy 4:6", "For I am now ready to be offered, and the time of my departure is at hand."],
["502", "2 Timothy 4:7", "I have fought a good fight, I have finished my course, I have kept the faith:"],
["503", "2 Timothy 4:8", "Henceforth there is laid up for me a crown of righteousness, which the Lord, the righteous judge, shall give me at that day: and not to me only, but unto all them also that love his appearing."],
["504", "2 Timothy 4:9", "Do thy diligence to come shortly unto me:"],
["505", "2 Timothy 4:10", "For Demas hath forsaken me, having loved this present world, and is departed unto Thessalonica; Crescens to Galatia, Titus unto Dalmatia."],
["506", "2 Timothy 4:11", "Only Luke is with me. Take Mark, and bring him with thee: for he is profitable to me for the ministry."],
["507", "2 Timothy 4:12", "And Tychicus have I sent to Ephesus."],
["508", "2 Timothy 4:13", "The cloke that I left at Troas with Carpus, when thou comest, bring with thee, and the books, but especially the parchments."],
["509", "2 Timothy 4:14", "Alexander the coppersmith did me much evil: the Lord reward him according to his works:"],
["510", "2 Timothy 4:15", "Of whom be thou ware also; for he hath greatly withstood our words."],
["511", "2 Timothy 4:16", "At my first answer no man stood with me, but all men forsook me: I pray God that it may not be laid to their charge."],
["512", "2 Timothy 4:17", "Notwithstanding the Lord stood with me, and strengthened me; that by me the preaching might be fully known, and that all the Gentiles might hear: and I was delivered out of the mouth of the lion."],
["513", "2 Timothy 4:18", "And the Lord shall deliver me from every evil work, and will preserve me unto his heavenly kingdom: to whom be glory for ever and ever. Amen."],
["514", "2 Timothy 4:19", "Salute Prisca and Aquila, and the household of Onesiphorus."],
["515", "2 Timothy 4:20", "Erastus abode at Corinth: but Trophimus have I left at Miletum sick."],
["516", "2 Timothy 4:21", "Do thy diligence to come before winter. Eubulus greeteth thee, and Pudens, and Linus, and Claudia, and all the brethren."],
["517", "2 Timothy 4:22", "The Lord Jesus Christ be with thy spirit. Grace be with you. Amen."]]
