/*
Greetings to whomever was curious about this code.

I know it is a horrible idea to manually encode the breakpoints and verses, but I made this site in a school computer lab in about half an hour in 2022, and I do not wish to refactor at this time.


Thank you,

Joshua Bays
*/

let masterList = [["1", "John 1:1", "In the beginning was the Word, and the Word was with God, and the Word was God."],
["2", "John 1:2", "The same was in the beginning with God."],
["3", "John 1:3", "All things were made by him; and without him was not any thing made that was made."],
["4", "John 1:4", "In him was life; and the life was the light of men."],
["5", "John 1:5", "And the light shineth in darkness; and the darkness comprehended it not."],
["6", "John 1:6", "There was a man sent from God, whose name was John."],
["7", "John 1:7", "The same came for a witness, to bear witness of the Light, that all men through him might believe."],
["8", "John 1:8", "He was not that Light, but was sent to bear witness of that Light."],
["9", "John 1:9", "That was the true Light, which lighteth every man that cometh into the world."],
["10", "John 1:10", "He was in the world, and the world was made by him, and the world knew him not."],
["11", "John 1:11", "He came unto his own, and his own received him not."],
["12", "John 1:12", "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:"],
["13", "John 1:13", "Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God."],
["14", "John 1:14", "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth."],
["15", "John 1:15", "John bare witness of him, and cried, saying, This was he of whom I spake, He that cometh after me is preferred before me: for he was before me."],
["16", "John 1:16", "And of his fulness have all we received, and grace for grace."],
["17", "John 1:17", "For the law was given by Moses, but grace and truth came by Jesus Christ."],
["18", "John 1:18", "No man hath seen God at any time; the only begotten Son, which is in the bosom of the Father, he hath declared him."],
["19", "Luke 1:5", "There was in the days of Herod, the king of Judaea, a certain priest named Zacharias, of the course of Abia: and his wife was of the daughters of Aaron, and her name was Elisabeth."],
["20", "Luke 1:6", "And they were both righteous before God, walking in all the commandments and ordinances of the Lord blameless."],
["21", "Luke 1:7", "And they had no child, because that Elisabeth was barren, and they both were now well stricken in years."],
["22", "Luke 1:8", "And it came to pass, that while he executed the priest's office before God in the order of his course,"],
["23", "Luke 1:9", "According to the custom of the priest's office, his lot was to burn incense when he went into the temple of the Lord."],
["24", "Luke 1:10", "And the whole multitude of the people were praying without at the time of incense."],
["25", "Luke 1:11", "And there appeared unto him an angel of the Lord standing on the right side of the altar of incense."],
["26", "Luke 1:12", "And when Zacharias saw him, he was troubled, and fear fell upon him."],
["27", "Luke 1:13", "But the angel said unto him, Fear not, Zacharias: for thy prayer is heard; and thy wife Elisabeth shall bear thee a son, and thou shalt call his name John."],
["28", "Luke 1:14", "And thou shalt have joy and gladness; and many shall rejoice at his birth."],
["29", "Luke 1:15", "For he shall be great in the sight of the Lord, and shall drink neither wine nor strong drink; and he shall be filled with the Holy Ghost, even from his mother's womb."],
["30", "Luke 1:16", "And many of the children of Israel shall he turn to the Lord their God."],
["31", "Luke 1:17", "And he shall go before him in the spirit and power of Elias, to turn the hearts of the fathers to the children, and the disobedient to the wisdom of the just; to make ready a people prepared for the Lord."],
["32", "Luke 1:18", "And Zacharias said unto the angel, Whereby shall I know this? for I am an old man, and my wife well stricken in years."],
["33", "Luke 1:19", "And the angel answering said unto him, I am Gabriel, that stand in the presence of God; and am sent to speak unto thee, and to shew thee these glad tidings."],
["34", "Luke 1:20", "And, behold, thou shalt be dumb, and not able to speak, until the day that these things shall be performed, because thou believest not my words, which shall be fulfilled in their season."],
["35", "Luke 1:21", "And the people waited for Zacharias, and marvelled that he tarried so long in the temple."],
["36", "Luke 1:22", "And when he came out, he could not speak unto them: and they perceived that he had seen a vision in the temple: for he beckoned unto them, and remained speechless."],
["37", "Luke 1:23", "And it came to pass, that, as soon as the days of his ministration were accomplished, he departed to his own house."],
["38", "Luke 1:24", "And after those days his wife Elisabeth conceived, and hid herself five months, saying,"],
["39", "Luke 1:25", "Thus hath the Lord dealt with me in the days wherein he looked on me, to take away my reproach among men."],
["40", "Luke 1:26", "And in the sixth month the angel Gabriel was sent from God unto a city of Galilee, named Nazareth,"],
["41", "Luke 1:27", "To a virgin espoused to a man whose name was Joseph, of the house of David; and the virgin's name was Mary."],
["42", "Luke 1:28", "And the angel came in unto her, and said, Hail, thou that art highly favoured, the Lord is with thee: blessed art thou among women."],
["43", "Luke 1:29", "And when she saw him, she was troubled at his saying, and cast in her mind what manner of salutation this should be."],
["44", "Luke 1:30", "And the angel said unto her, Fear not, Mary: for thou hast found favour with God."],
["45", "Luke 1:31", "And, behold, thou shalt conceive in thy womb, and bring forth a son, and shalt call his name JESUS."],
["46", "Luke 1:32", "He shall be great, and shall be called the Son of the Highest: and the Lord God shall give unto him the throne of his father David:"],
["47", "Luke 1:33", "And he shall reign over the house of Jacob for ever; and of his kingdom there shall be no end."],
["48", "Luke 1:34", "Then said Mary unto the angel, How shall this be, seeing I know not a man?"],
["49", "Luke 1:35", "And the angel answered and said unto her, The Holy Ghost shall come upon thee, and the power of the Highest shall overshadow thee: therefore also that holy thing which shall be born of thee shall be called the Son of God."],
["50", "Luke 1:36", "And, behold, thy cousin Elisabeth, she hath also conceived a son in her old age: and this is the sixth month with her, who was called barren."],
["51", "Luke 1:37", "For with God nothing shall be impossible."],
["52", "Luke 1:38", "And Mary said, Behold the handmaid of the Lord; be it unto me according to thy word. And the angel departed from her."],
["53", "Luke 1:39", "And Mary arose in those days, and went into the hill country with haste, into a city of Juda;"],
["54", "Luke 1:40", "And entered into the house of Zacharias, and saluted Elisabeth."],
["55", "Luke 1:41", "And it came to pass, that, when Elisabeth heard the salutation of Mary, the babe leaped in her womb; and Elisabeth was filled with the Holy Ghost:"],
["56", "Luke 1:42", "And she spake out with a loud voice, and said, Blessed art thou among women, and blessed is the fruit of thy womb."],
["57", "Luke 1:43", "And whence is this to me, that the mother of my Lord should come to me?"],
["58", "Luke 1:44", "For, lo, as soon as the voice of thy salutation sounded in mine ears, the babe leaped in my womb for joy."],
["59", "Luke 1:45", "And blessed is she that believed: for there shall be a performance of those things which were told her from the Lord."],
["60", "Luke 1:46", "And Mary said, My soul doth magnify the Lord,"],
["61", "Luke 1:47", "And my spirit hath rejoiced in God my Saviour."],
["62", "Luke 1:48", "For he hath regarded the low estate of his handmaiden: for, behold, from henceforth all generations shall call me blessed."],
["63", "Luke 1:49", "For he that is mighty hath done to me great things; and holy is his name."],
["64", "Luke 1:50", "And his mercy is on them that fear him from generation to generation."],
["65", "Luke 1:51", "He hath shewed strength with his arm; he hath scattered the proud in the imagination of their hearts."],
["66", "Luke 1:52", "He hath put down the mighty from their seats, and exalted them of low degree."],
["67", "Luke 1:53", "He hath filled the hungry with good things; and the rich he hath sent empty away."],
["68", "Luke 1:54", "He hath holpen his servant Israel, in remembrance of his mercy;"],
["69", "Luke 1:55", "As he spake to our fathers, to Abraham, and to his seed for ever."],
["70", "Luke 1:56", "And Mary abode with her about three months, and returned to her own house."],
["71", "Luke 1:57", "Now Elisabeth's full time came that she should be delivered; and she brought forth a son."],
["72", "Luke 1:58", "And her neighbours and her cousins heard how the Lord had shewed great mercy upon her; and they rejoiced with her."],
["73", "Luke 1:59", "And it came to pass, that on the eighth day they came to circumcise the child; and they called him Zacharias, after the name of his father."],
["74", "Luke 1:60", "And his mother answered and said, Not so; but he shall be called John."],
["75", "Luke 1:61", "And they said unto her, There is none of thy kindred that is called by this name."],
["76", "Luke 1:62", "And they made signs to his father, how he would have him called."],
["77", "Luke 1:63", "And he asked for a writing table, and wrote, saying, His name is John. And they marvelled all."],
["78", "Luke 1:64", "And his mouth was opened immediately, and his tongue loosed, and he spake, and praised God."],
["79", "Luke 1:65", "And fear came on all that dwelt round about them: and all these sayings were noised abroad throughout all the hill country of Judaea."],
["80", "Luke 1:66", "And all they that heard them laid them up in their hearts, saying, What manner of child shall this be! And the hand of the Lord was with him."],
["81", "Luke 1:67", "And his father Zacharias was filled with the Holy Ghost, and prophesied, saying,"],
["82", "Luke 1:68", "Blessed be the Lord God of Israel; for he hath visited and redeemed his people,"],
["83", "Luke 1:69", "And hath raised up an horn of salvation for us in the house of his servant David;"],
["84", "Luke 1:70", "As he spake by the mouth of his holy prophets, which have been since the world began:"],
["85", "Luke 1:71", "That we should be saved from our enemies, and from the hand of all that hate us;"],
["86", "Luke 1:72", "To perform the mercy promised to our fathers, and to remember his holy covenant;"],
["87", "Luke 1:73", "The oath which he sware to our father Abraham,"],
["88", "Luke 1:74", "That he would grant unto us, that we being delivered out of the hand of our enemies might serve him without fear,"],
["89", "Luke 1:75", "In holiness and righteousness before him, all the days of our life."],
["90", "Luke 1:76", "And thou, child, shalt be called the prophet of the Highest: for thou shalt go before the face of the Lord to prepare his ways;"],
["91", "Luke 1:77", "To give knowledge of salvation unto his people by the remission of their sins,"],
["92", "Luke 1:78", "Through the tender mercy of our God; whereby the dayspring from on high hath visited us,"],
["93", "Luke 1:79", "To give light to them that sit in darkness and in the shadow of death, to guide our feet into the way of peace."],
["94", "Luke 1:80", "And the child grew, and waxed strong in spirit, and was in the deserts till the day of his shewing unto Israel."],
["95", "Matthew 1:18", "Now the birth of Jesus Christ was on this wise: When as his mother Mary was espoused to Joseph, before they came together, she was found with child of the Holy Ghost."],
["96", "Matthew 1:19", "Then Joseph her husband, being a just man, and not willing to make her a publick example, was minded to put her away privily."],
["97", "Matthew 1:20", "But while he thought on these things, behold, the angel of the LORD appeared unto him in a dream, saying, Joseph, thou son of David, fear not to take unto thee Mary thy wife: for that which is conceived in her is of the Holy Ghost."],
["98", "Matthew 1:21", "And she shall bring forth a son, and thou shalt call his name JESUS: for he shall save his people from their sins."],
["99", "Matthew 1:22", "Now all this was done, that it might be fulfilled which was spoken of the Lord by the prophet, saying,"],
["100", "Matthew 1:23", "Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us."],
["101", "Matthew 1:24", "Then Joseph being raised from sleep did as the angel of the Lord had bidden him, and took unto him his wife:"],
["102", "Matthew 1:25", "And knew her not till she had brought forth her firstborn son: and he called his name JESUS."],
["103", "Luke 2:1", "And it came to pass in those days, that there went out a decree from Caesar Augustus, that all the world should be taxed."],
["104", "Luke 2:2", "(And this taxing was first made when Cyrenius was governor of Syria.)"],
["105", "Luke 2:3", "And all went to be taxed, every one into his own city."],
["106", "Luke 2:4", "And Joseph also went up from Galilee, out of the city of Nazareth, into Judaea, unto the city of David, which is called Bethlehem; (because he was of the house and lineage of David:)"],
["107", "Luke 2:5", "To be taxed with Mary his espoused wife, being great with child."],
["108", "Luke 2:6", "And so it was, that, while they were there, the days were accomplished that she should be delivered."],
["109", "Luke 2:7", "And she brought forth her firstborn son, and wrapped him in swaddling clothes, and laid him in a manger; because there was no room for them in the inn."],
["110", "Luke 2:8", "And there were in the same country shepherds abiding in the field, keeping watch over their flock by night."],
["111", "Luke 2:9", "And, lo, the angel of the Lord came upon them, and the glory of the Lord shone round about them: and they were sore afraid."],
["112", "Luke 2:10", "And the angel said unto them, Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people."],
["113", "Luke 2:11", "For unto you is born this day in the city of David a Saviour, which is Christ the Lord."],
["114", "Luke 2:12", "And this shall be a sign unto you; Ye shall find the babe wrapped in swaddling clothes, lying in a manger."],
["115", "Luke 2:13", "And suddenly there was with the angel a multitude of the heavenly host praising God, and saying,"],
["116", "Luke 2:14", "Glory to God in the highest, and on earth peace, good will toward men."],
["117", "Luke 2:15", "And it came to pass, as the angels were gone away from them into heaven, the shepherds said one to another, Let us now go even unto Bethlehem, and see this thing which is come to pass, which the Lord hath made known unto us."],
["118", "Luke 2:16", "And they came with haste, and found Mary, and Joseph, and the babe lying in a manger."],
["119", "Luke 2:17", "And when they had seen it, they made known abroad the saying which was told them concerning this child."],
["120", "Luke 2:18", "And all they that heard it wondered at those things which were told them by the shepherds."],
["121", "Luke 2:19", "But Mary kept all these things, and pondered them in her heart."],
["122", "Luke 2:20", "And the shepherds returned, glorifying and praising God for all the things that they had heard and seen, as it was told unto them."],
["123", "Luke 2:21", "And when eight days were accomplished for the circumcising of the child, his name was called JESUS, which was so named of the angel before he was conceived in the womb."],
["124", "Luke 2:22", "And when the days of her purification according to the law of Moses were accomplished, they brought him to Jerusalem, to present him to the Lord;"],
["125", "Luke 2:23", "(As it is written in the law of the LORD, Every male that openeth the womb shall be called holy to the Lord;)"],
["126", "Luke 2:24", "And to offer a sacrifice according to that which is said in the law of the Lord, A pair of turtledoves, or two young pigeons."],
["127", "Luke 2:25", "And, behold, there was a man in Jerusalem, whose name was Simeon; and the same man was just and devout, waiting for the consolation of Israel: and the Holy Ghost was upon him."],
["128", "Luke 2:26", "And it was revealed unto him by the Holy Ghost, that he should not see death, before he had seen the Lord's Christ."],
["129", "Luke 2:27", "And he came by the Spirit into the temple: and when the parents brought in the child Jesus, to do for him after the custom of the law,"],
["130", "Luke 2:28", "Then took he him up in his arms, and blessed God, and said,"],
["131", "Luke 2:29", "Lord, now lettest thou thy servant depart in peace, according to thy word:"],
["132", "Luke 2:30", "For mine eyes have seen thy salvation,"],
["133", "Luke 2:31", "Which thou hast prepared before the face of all people;"],
["134", "Luke 2:32", "A light to lighten the Gentiles, and the glory of thy people Israel."],
["135", "Luke 2:33", "And Joseph and his mother marvelled at those things which were spoken of him."],
["136", "Luke 2:34", "And Simeon blessed them, and said unto Mary his mother, Behold, this child is set for the fall and rising again of many in Israel; and for a sign which shall be spoken against;"],
["137", "Luke 2:35", "(Yea, a sword shall pierce through thy own soul also,) that the thoughts of many hearts may be revealed."],
["138", "Luke 2:36", "And there was one Anna, a prophetess, the daughter of Phanuel, of the tribe of Aser: she was of a great age, and had lived with an husband seven years from her virginity;"],
["139", "Luke 2:37", "And she was a widow of about fourscore and four years, which departed not from the temple, but served God with fastings and prayers night and day."],
["140", "Luke 2:38", "And she coming in that instant gave thanks likewise unto the Lord, and spake of him to all them that looked for redemption in Jerusalem."],
["141", "Matthew 2:1", "Now when Jesus was born in Bethlehem of Judaea in the days of Herod the king, behold, there came wise men from the east to Jerusalem,"],
["142", "Matthew 2:2", "Saying, Where is he that is born King of the Jews? for we have seen his star in the east, and are come to worship him."],
["143", "Matthew 2:3", "When Herod the king had heard these things, he was troubled, and all Jerusalem with him."],
["144", "Matthew 2:4", "And when he had gathered all the chief priests and scribes of the people together, he demanded of them where Christ should be born."],
["145", "Matthew 2:5", "And they said unto him, In Bethlehem of Judaea: for thus it is written by the prophet,"],
["146", "Matthew 2:6", "And thou Bethlehem, in the land of Juda, art not the least among the princes of Juda: for out of thee shall come a Governor, that shall rule my people Israel."],
["147", "Matthew 2:7", "Then Herod, when he had privily called the wise men, enquired of them diligently what time the star appeared."],
["148", "Matthew 2:8", "And he sent them to Bethlehem, and said, Go and search diligently for the young child; and when ye have found him, bring me word again, that I may come and worship him also."],
["149", "Matthew 2:9", "When they had heard the king, they departed; and, lo, the star, which they saw in the east, went before them, till it came and stood over where the young child was."],
["150", "Matthew 2:10", "When they saw the star, they rejoiced with exceeding great joy."],
["151", "Matthew 2:11", "And when they were come into the house, they saw the young child with Mary his mother, and fell down, and worshipped him: and when they had opened their treasures, they presented unto him gifts; gold, and frankincense, and myrrh."],
["152", "Matthew 2:12", "And being warned of God in a dream that they should not return to Herod, they departed into their own country another way."],
["153", "Matthew 2:13", "And when they were departed, behold, the angel of the Lord appeareth to Joseph in a dream, saying, Arise, and take the young child and his mother, and flee into Egypt, and be thou there until I bring thee word: for Herod will seek the young child to destroy him."],
["154", "Matthew 2:14", "When he arose, he took the young child and his mother by night, and departed into Egypt:"],
["155", "Matthew 2:15", "And was there until the death of Herod: that it might be fulfilled which was spoken of the Lord by the prophet, saying, Out of Egypt have I called my son."],
["156", "Matthew 2:16", "Then Herod, when he saw that he was mocked of the wise men, was exceeding wroth, and sent forth, and slew all the children that were in Bethlehem, and in all the coasts thereof, from two years old and under, according to the time which he had diligently enquired of the wise men."],
["157", "Matthew 2:17", "Then was fulfilled that which was spoken by Jeremy the prophet, saying,"],
["158", "Matthew 2:18", "In Rama was there a voice heard, lamentation, and weeping, and great mourning, Rachel weeping for her children, and would not be comforted, because they are not."],
["159", "Matthew 2:19", "But when Herod was dead, behold, an angel of the Lord appeareth in a dream to Joseph in Egypt,"],
["160", "Matthew 2:20", "Saying, Arise, and take the young child and his mother, and go into the land of Israel: for they are dead which sought the young child's life."],
["161", "Matthew 2:21", "And he arose, and took the young child and his mother, and came into the land of Israel."],
["162", "Matthew 2:22", "But when he heard that Archelaus did reign in Judaea in the room of his father Herod, he was afraid to go thither: notwithstanding, being warned of God in a dream, he turned aside into the parts of Galilee:"],
["163", "Matthew 2:23", "And he came and dwelt in a city called Nazareth: that it might be fulfilled which was spoken by the prophets, He shall be called a Nazarene."],
["164", "Luke 2:40", "And the child grew, and waxed strong in spirit, filled with wisdom: and the grace of God was upon him."],
["165", "Luke 2:41", "Now his parents went to Jerusalem every year at the feast of the passover."],
["166", "Luke 2:42", "And when he was twelve years old, they went up to Jerusalem after the custom of the feast."],
["167", "Luke 2:43", "And when they had fulfilled the days, as they returned, the child Jesus tarried behind in Jerusalem; and Joseph and his mother knew not of it."],
["168", "Luke 2:44", "But they, supposing him to have been in the company, went a day's journey; and they sought him among their kinsfolk and acquaintance."],
["169", "Luke 2:45", "And when they found him not, they turned back again to Jerusalem, seeking him."],
["170", "Luke 2:46", "And it came to pass, that after three days they found him in the temple, sitting in the midst of the doctors, both hearing them, and asking them questions."],
["171", "Luke 2:47", "And all that heard him were astonished at his understanding and answers."],
["172", "Luke 2:48", "And when they saw him, they were amazed: and his mother said unto him, Son, why hast thou thus dealt with us? behold, thy father and I have sought thee sorrowing."],
["173", "Luke 2:49", "And he said unto them, How is it that ye sought me? wist ye not that I must be about my Father's business?"],
["174", "Luke 2:50", "And they understood not the saying which he spake unto them."],
["175", "Luke 2:51", "And he went down with them, and came to Nazareth, and was subject unto them: but his mother kept all these sayings in her heart."],
["176", "Luke 2:52", "And Jesus increased in wisdom and stature, and in favour with God and man."],
["177", "Matthew 3:1", "In those days came John the Baptist, preaching in the wilderness of Judaea,"],
["178", "Matthew 3:2", "And saying, Repent ye: for the kingdom of heaven is at hand."],
["179", "Matthew 3:3", "For this is he that was spoken of by the prophet Esaias, saying, The voice of one crying in the wilderness, Prepare ye the way of the Lord, make his paths straight."],
["180", "Matthew 3:4", "And the same John had his raiment of camel's hair, and a leathern girdle about his loins; and his meat was locusts and wild honey."],
["181", "Matthew 3:5", "Then went out to him Jerusalem, and all Judaea, and all the region round about Jordan,"],
["182", "Matthew 3:6", "And were baptized of him in Jordan, confessing their sins."],
["183", "Matthew 3:7", "But when he saw many of the Pharisees and Sadducees come to his baptism, he said unto them, O generation of vipers, who hath warned you to flee from the wrath to come?"],
["184", "Matthew 3:8", "Bring forth therefore fruits meet for repentance:"],
["185", "Matthew 3:9", "And think not to say within yourselves, We have Abraham to our father: for I say unto you, that God is able of these stones to raise up children unto Abraham."],
["186", "Matthew 3:10", "And now also the axe is laid unto the root of the trees: therefore every tree which bringeth not forth good fruit is hewn down, and cast into the fire."],
["187", "Luke 3:15", "And as the people were in expectation, and all men mused in their hearts of John, whether he were the Christ, or not;"],
["188", "Luke 3:16", "John answered, saying unto them all, I indeed baptize you with water; but one mightier than I cometh, the latchet of whose shoes I am not worthy to unloose: he shall baptize you with the Holy Ghost and with fire:"],
["189", "Luke 3:17", "Whose fan is in his hand, and he will throughly purge his floor, and will gather the wheat into his garner; but the chaff he will burn with fire unquenchable."],
["190", "Luke 3:18", "And many other things in his exhortation preached he unto the people."],
["191", "Matthew 3:13", "Then cometh Jesus from Galilee to Jordan unto John, to be baptized of him."],
["192", "Matthew 3:14", "But John forbad him, saying, I have need to be baptized of thee, and comest thou to me?"],
["193", "Matthew 3:15", "And Jesus answering said unto him, Suffer it to be so now: for thus it becometh us to fulfil all righteousness. Then he suffered him."],
["194", "Matthew 3:16", "And Jesus, when he was baptized, went up straightway out of the water: and, lo, the heavens were opened unto him, and he saw the Spirit of God descending like a dove, and lighting upon him:"],
["195", "Matthew 3:17", "And lo a voice from heaven, saying, This is my beloved Son, in whom I am well pleased."],
["196", "Luke 3:23", "And Jesus himself began to be about thirty years of age, being (as was supposed) the son of Joseph, which was the son of Heli,"],
["197", "Matthew 4:1", "Then was Jesus led up of the Spirit into the wilderness to be tempted of the devil."],
["198", "Matthew 4:2", "And when he had fasted forty days and forty nights, he was afterward an hungred."],
["199", "Matthew 4:3", "And when the tempter came to him, he said, If thou be the Son of God, command that these stones be made bread."],
["200", "Matthew 4:4", "But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God."],
["201", "Matthew 4:5", "Then the devil taketh him up into the holy city, and setteth him on a pinnacle of the temple,"],
["202", "Matthew 4:6", "And saith unto him, If thou be the Son of God, cast thyself down: for it is written, He shall give his angels charge concerning thee: and in their hands they shall bear thee up, lest at any time thou dash thy foot against a stone."],
["203", "Matthew 4:7", "Jesus said unto him, It is written again, Thou shalt not tempt the Lord thy God."],
["204", "Matthew 4:8", "Again, the devil taketh him up into an exceeding high mountain, and sheweth him all the kingdoms of the world, and the glory of them;"],
["205", "Matthew 4:9", "And saith unto him, All these things will I give thee, if thou wilt fall down and worship me."],
["206", "Matthew 4:10", "Then saith Jesus unto him, Get thee hence, Satan: for it is written, Thou shalt worship the Lord thy God, and him only shalt thou serve."],
["207", "Matthew 4:11", "Then the devil leaveth him, and, behold, angels came and ministered unto him."],
["208", "John 1:19", "And this is the record of John, when the Jews sent priests and Levites from Jerusalem to ask him, Who art thou?"],
["209", "John 1:20", "And he confessed, and denied not; but confessed, I am not the Christ."],
["210", "John 1:21", "And they asked him, What then? Art thou Elias? And he saith, I am not. Art thou that prophet? And he answered, No."],
["211", "John 1:22", "Then said they unto him, Who art thou? that we may give an answer to them that sent us. What sayest thou of thyself?"],
["212", "John 1:23", "He said, I am the voice of one crying in the wilderness, Make straight the way of the Lord, as said the prophet Esaias."],
["213", "John 1:24", "And they which were sent were of the Pharisees."],
["214", "John 1:25", "And they asked him, and said unto him, Why baptizest thou then, if thou be not that Christ, nor Elias, neither that prophet?"],
["215", "John 1:26", "John answered them, saying, I baptize with water: but there standeth one among you, whom ye know not;"],
["216", "John 1:27", "He it is, who coming after me is preferred before me, whose shoe's latchet I am not worthy to unloose."],
["217", "John 1:28", "These things were done in Bethabara beyond Jordan, where John was baptizing."],
["218", "John 1:29", "The next day John seeth Jesus coming unto him, and saith, Behold the Lamb of God, which taketh away the sin of the world."],
["219", "John 1:30", "This is he of whom I said, After me cometh a man which is preferred before me: for he was before me."],
["220", "John 1:31", "And I knew him not: but that he should be made manifest to Israel, therefore am I come baptizing with water."],
["221", "John 1:32", "And John bare record, saying, I saw the Spirit descending from heaven like a dove, and it abode upon him."],
["222", "John 1:33", "And I knew him not: but he that sent me to baptize with water, the same said unto me, Upon whom thou shalt see the Spirit descending, and remaining on him, the same is he which baptizeth with the Holy Ghost."],
["223", "John 1:34", "And I saw, and bare record that this is the Son of God."],
["224", "John 1:35", "Again the next day after John stood, and two of his disciples;"],
["225", "John 1:36", "And looking upon Jesus as he walked, he saith, Behold the Lamb of God!"],
["226", "John 1:37", "And the two disciples heard him speak, and they followed Jesus."],
["227", "John 1:38", "Then Jesus turned, and saw them following, and saith unto them, What seek ye? They said unto him, Rabbi, (which is to say, being interpreted, Master,) where dwellest thou?"],
["228", "John 1:39", "He saith unto them, Come and see. They came and saw where he dwelt, and abode with him that day: for it was about the tenth hour."],
["229", "John 1:40", "One of the two which heard John speak, and followed him, was Andrew, Simon Peter's brother."],
["230", "John 1:41", "He first findeth his own brother Simon, and saith unto him, We have found the Messias, which is, being interpreted, the Christ."],
["231", "John 1:42", "And he brought him to Jesus. And when Jesus beheld him, he said, Thou art Simon the son of Jona: thou shalt be called Cephas, which is by interpretation, A stone."],
["232", "John 1:43", "The day following Jesus would go forth into Galilee, and findeth Philip, and saith unto him, Follow me."],
["233", "John 1:44", "Now Philip was of Bethsaida, the city of Andrew and Peter."],
["234", "John 1:45", "Philip findeth Nathanael, and saith unto him, We have found him, of whom Moses in the law, and the prophets, did write, Jesus of Nazareth, the son of Joseph."],
["235", "John 1:46", "And Nathanael said unto him, Can there any good thing come out of Nazareth? Philip saith unto him, Come and see."],
["236", "John 1:47", "Jesus saw Nathanael coming to him, and saith of him, Behold an Israelite indeed, in whom is no guile!"],
["237", "John 1:48", "Nathanael saith unto him, Whence knowest thou me? Jesus answered and said unto him, Before that Philip called thee, when thou wast under the fig tree, I saw thee."],
["238", "John 1:49", "Nathanael answered and saith unto him, Rabbi, thou art the Son of God; thou art the King of Israel."],
["239", "John 1:50", "Jesus answered and said unto him, Because I said unto thee, I saw thee under the fig tree, believest thou? thou shalt see greater things than these."],
["240", "John 1:51", "And he saith unto him, Verily, verily, I say unto you, Hereafter ye shall see heaven open, and the angels of God ascending and descending upon the Son of man."],
["241", "John 2:1", "And the third day there was a marriage in Cana of Galilee; and the mother of Jesus was there:"],
["242", "John 2:2", "And both Jesus was called, and his disciples, to the marriage."],
["243", "John 2:3", "And when they wanted wine, the mother of Jesus saith unto him, They have no wine."],
["244", "John 2:4", "Jesus saith unto her, Woman, what have I to do with thee? mine hour is not yet come."],
["245", "John 2:5", "His mother saith unto the servants, Whatsoever he saith unto you, do it."],
["246", "John 2:6", "And there were set there six waterpots of stone, after the manner of the purifying of the Jews, containing two or three firkins apiece."],
["247", "John 2:7", "Jesus saith unto them, Fill the waterpots with water. And they filled them up to the brim."],
["248", "John 2:8", "And he saith unto them, Draw out now, and bear unto the governor of the feast. And they bare it."],
["249", "John 2:9", "When the ruler of the feast had tasted the water that was made wine, and knew not whence it was: (but the servants which drew the water knew;) the governor of the feast called the bridegroom,"],
["250", "John 2:10", "And saith unto him, Every man at the beginning doth set forth good wine; and when men have well drunk, then that which is worse: but thou hast kept the good wine until now."],
["251", "John 2:11", "This beginning of miracles did Jesus in Cana of Galilee, and manifested forth his glory; and his disciples believed on him."],
["252", "John 2:12", "After this he went down to Capernaum, he, and his mother, and his brethren, and his disciples: and they continued there not many days."],
["253", "John 2:13", "And the Jews' passover was at hand, and Jesus went up to Jerusalem,"],
["254", "John 2:14", "And found in the temple those that sold oxen and sheep and doves, and the changers of money sitting:"],
["255", "John 2:15", "And when he had made a scourge of small cords, he drove them all out of the temple, and the sheep, and the oxen; and poured out the changers' money, and overthrew the tables;"],
["256", "John 2:16", "And said unto them that sold doves, Take these things hence; make not my Father's house an house of merchandise."],
["257", "John 2:17", "And his disciples remembered that it was written, The zeal of thine house hath eaten me up."],
["258", "John 2:18", "Then answered the Jews and said unto him, What sign shewest thou unto us, seeing that thou doest these things?"],
["259", "John 2:19", "Jesus answered and said unto them, Destroy this temple, and in three days I will raise it up."],
["260", "John 2:20", "Then said the Jews, Forty and six years was this temple in building, and wilt thou rear it up in three days?"],
["261", "John 2:21", "But he spake of the temple of his body."],
["262", "John 2:22", "When therefore he was risen from the dead, his disciples remembered that he had said this unto them; and they believed the scripture, and the word which Jesus had said."],
["263", "John 2:23", "Now when he was in Jerusalem at the passover, in the feast day, many believed in his name, when they saw the miracles which he did."],
["264", "John 2:24", "But Jesus did not commit himself unto them, because he knew all men,"],
["265", "John 2:25", "And needed not that any should testify of man: for he knew what was in man."],
["266", "John 3:1", "There was a man of the Pharisees, named Nicodemus, a ruler of the Jews:"],
["267", "John 3:2", "The same came to Jesus by night, and said unto him, Rabbi, we know that thou art a teacher come from God: for no man can do these miracles that thou doest, except God be with him."],
["268", "John 3:3", "Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God."],
["269", "John 3:4", "Nicodemus saith unto him, How can a man be born when he is old? can he enter the second time into his mother's womb, and be born?"],
["270", "John 3:5", "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God."],
["271", "John 3:6", "That which is born of the flesh is flesh; and that which is born of the Spirit is spirit."],
["272", "John 3:7", "Marvel not that I said unto thee, Ye must be born again."],
["273", "John 3:8", "The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit."],
["274", "John 3:9", "Nicodemus answered and said unto him, How can these things be?"],
["275", "John 3:10", "Jesus answered and said unto him, Art thou a master of Israel, and knowest not these things?"],
["276", "John 3:11", "Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness."],
["277", "John 3:12", "If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you of heavenly things?"],
["278", "John 3:13", "And no man hath ascended up to heaven, but he that came down from heaven, even the Son of man which is in heaven."],
["279", "John 3:14", "And as Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up:"],
["280", "John 3:15", "That whosoever believeth in him should not perish, but have eternal life."],
["281", "John 3:16", "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."],
["282", "John 3:17", "For God sent not his Son into the world to condemn the world; but that the world through him might be saved."],
["283", "John 3:18", "He that believeth on him is not condemned: but he that believeth not is condemned already, because he hath not believed in the name of the only begotten Son of God."],
["284", "John 3:19", "And this is the condemnation, that light is come into the world, and men loved darkness rather than light, because their deeds were evil."],
["285", "John 3:20", "For every one that doeth evil hateth the light, neither cometh to the light, lest his deeds should be reproved."],
["286", "John 3:21", "But he that doeth truth cometh to the light, that his deeds may be made manifest, that they are wrought in God."],
["287", "John 3:22", "After these things came Jesus and his disciples into the land of Judaea; and there he tarried with them, and baptized."],
["288", "John 3:23", "And John also was baptizing in Aenon near to Salim, because there was much water there: and they came, and were baptized."],
["289", "John 3:24", "For John was not yet cast into prison."],
["290", "John 3:25", "Then there arose a question between some of John's disciples and the Jews about purifying."],
["291", "John 3:26", "And they came unto John, and said unto him, Rabbi, he that was with thee beyond Jordan, to whom thou barest witness, behold, the same baptizeth, and all men come to him."],
["292", "John 3:27", "John answered and said, A man can receive nothing, except it be given him from heaven."],
["293", "John 3:28", "Ye yourselves bear me witness, that I said, I am not the Christ, but that I am sent before him."],
["294", "John 3:29", "He that hath the bride is the bridegroom: but the friend of the bridegroom, which standeth and heareth him, rejoiceth greatly because of the bridegroom's voice: this my joy therefore is fulfilled."],
["295", "John 3:30", "He must increase, but I must decrease."],
["296", "John 3:31", "He that cometh from above is above all: he that is of the earth is earthly, and speaketh of the earth: he that cometh from heaven is above all."],
["297", "John 3:32", "And what he hath seen and heard, that he testifieth; and no man receiveth his testimony."],
["298", "John 3:33", "He that hath received his testimony hath set to his seal that God is true."],
["299", "John 3:34", "For he whom God hath sent speaketh the words of God: for God giveth not the Spirit by measure unto him."],
["300", "John 3:35", "The Father loveth the Son, and hath given all things into his hand."],
["301", "John 3:36", "He that believeth on the Son hath everlasting life: and he that believeth not the Son shall not see life; but the wrath of God abideth on him."],
["302", "John 4:1", "When therefore the LORD knew how the Pharisees had heard that Jesus made and baptized more disciples than John,"],
["303", "John 4:2", "(Though Jesus himself baptized not, but his disciples,)"],
["304", "John 4:3", "He left Judaea, and departed again into Galilee."],
["305", "John 4:4", "And he must needs go through Samaria."],
["306", "John 4:5", "Then cometh he to a city of Samaria, which is called Sychar, near to the parcel of ground that Jacob gave to his son Joseph."],
["307", "John 4:6", "Now Jacob's well was there. Jesus therefore, being wearied with his journey, sat thus on the well: and it was about the sixth hour."],
["308", "John 4:7", "There cometh a woman of Samaria to draw water: Jesus saith unto her, Give me to drink."],
["309", "John 4:8", "(For his disciples were gone away unto the city to buy meat.)"],
["310", "John 4:9", "Then saith the woman of Samaria unto him, How is it that thou, being a Jew, askest drink of me, which am a woman of Samaria? for the Jews have no dealings with the Samaritans."],
["311", "John 4:10", "Jesus answered and said unto her, If thou knewest the gift of God, and who it is that saith to thee, Give me to drink; thou wouldest have asked of him, and he would have given thee living water."],
["312", "John 4:11", "The woman saith unto him, Sir, thou hast nothing to draw with, and the well is deep: from whence then hast thou that living water?"],
["313", "John 4:12", "Art thou greater than our father Jacob, which gave us the well, and drank thereof himself, and his children, and his cattle?"],
["314", "John 4:13", "Jesus answered and said unto her, Whosoever drinketh of this water shall thirst again:"],
["315", "John 4:14", "But whosoever drinketh of the water that I shall give him shall never thirst; but the water that I shall give him shall be in him a well of water springing up into everlasting life."],
["316", "John 4:15", "The woman saith unto him, Sir, give me this water, that I thirst not, neither come hither to draw."],
["317", "John 4:16", "Jesus saith unto her, Go, call thy husband, and come hither."],
["318", "John 4:17", "The woman answered and said, I have no husband. Jesus said unto her, Thou hast well said, I have no husband:"],
["319", "John 4:18", "For thou hast had five husbands; and he whom thou now hast is not thy husband: in that saidst thou truly."],
["320", "John 4:19", "The woman saith unto him, Sir, I perceive that thou art a prophet."],
["321", "John 4:20", "Our fathers worshipped in this mountain; and ye say, that in Jerusalem is the place where men ought to worship."],
["322", "John 4:21", "Jesus saith unto her, Woman, believe me, the hour cometh, when ye shall neither in this mountain, nor yet at Jerusalem, worship the Father."],
["323", "John 4:22", "Ye worship ye know not what: we know what we worship: for salvation is of the Jews."],
["324", "John 4:23", "But the hour cometh, and now is, when the true worshippers shall worship the Father in spirit and in truth: for the Father seeketh such to worship him."],
["325", "John 4:24", "God is a Spirit: and they that worship him must worship him in spirit and in truth."],
["326", "John 4:25", "The woman saith unto him, I know that Messias cometh, which is called Christ: when he is come, he will tell us all things."],
["327", "John 4:26", "Jesus saith unto her, I that speak unto thee am he."],
["328", "John 4:27", "And upon this came his disciples, and marvelled that he talked with the woman: yet no man said, What seekest thou? or, Why talkest thou with her?"],
["329", "John 4:28", "The woman then left her waterpot, and went her way into the city, and saith to the men,"],
["330", "John 4:29", "Come, see a man, which told me all things that ever I did: is not this the Christ?"],
["331", "John 4:30", "Then they went out of the city, and came unto him."],
["332", "John 4:31", "In the mean while his disciples prayed him, saying, Master, eat."],
["333", "John 4:32", "But he said unto them, I have meat to eat that ye know not of."],
["334", "John 4:33", "Therefore said the disciples one to another, Hath any man brought him ought to eat?"],
["335", "John 4:34", "Jesus saith unto them, My meat is to do the will of him that sent me, and to finish his work."],
["336", "John 4:35", "Say not ye, There are yet four months, and then cometh harvest? behold, I say unto you, Lift up your eyes, and look on the fields; for they are white already to harvest."],
["337", "John 4:36", "And he that reapeth receiveth wages, and gathereth fruit unto life eternal: that both he that soweth and he that reapeth may rejoice together."],
["338", "John 4:37", "And herein is that saying true, One soweth, and another reapeth."],
["339", "John 4:38", "I sent you to reap that whereon ye bestowed no labour: other men laboured, and ye are entered into their labours."],
["340", "John 4:39", "And many of the Samaritans of that city believed on him for the saying of the woman, which testified, He told me all that ever I did."],
["341", "John 4:40", "So when the Samaritans were come unto him, they besought him that he would tarry with them: and he abode there two days."],
["342", "John 4:41", "And many more believed because of his own word;"],
["343", "John 4:42", "And said unto the woman, Now we believe, not because of thy saying: for we have heard him ourselves, and know that this is indeed the Christ, the Saviour of the world."],
["344", "John 4:43", "Now after two days he departed thence, and went into Galilee."],
["345", "John 4:44", "For Jesus himself testified, that a prophet hath no honour in his own country."],
["346", "John 4:45", "Then when he was come into Galilee, the Galilaeans received him, having seen all the things that he did at Jerusalem at the feast: for they also went unto the feast."],
["347", "Mark 1:14", "Now after that John was put in prison, Jesus came into Galilee, preaching the gospel of the kingdom of God,"],
["348", "Mark 1:15", "And saying, The time is fulfilled, and the kingdom of God is at hand: repent ye, and believe the gospel."],
["349", "John 4:46", "So Jesus came again into Cana of Galilee, where he made the water wine. And there was a certain nobleman, whose son was sick at Capernaum."],
["350", "John 4:47", "When he heard that Jesus was come out of Judaea into Galilee, he went unto him, and besought him that he would come down, and heal his son: for he was at the point of death."],
["351", "John 4:48", "Then said Jesus unto him, Except ye see signs and wonders, ye will not believe."],
["352", "John 4:49", "The nobleman saith unto him, Sir, come down ere my child die."],
["353", "John 4:50", "Jesus saith unto him, Go thy way; thy son liveth. And the man believed the word that Jesus had spoken unto him, and he went his way."],
["354", "John 4:51", "And as he was now going down, his servants met him, and told him, saying, Thy son liveth."],
["355", "John 4:52", "Then enquired he of them the hour when he began to amend. And they said unto him, Yesterday at the seventh hour the fever left him."],
["356", "John 4:53", "So the father knew that it was at the same hour, in the which Jesus said unto him, Thy son liveth: and himself believed, and his whole house."],
["357", "John 4:54", "This is again the second miracle that Jesus did, when he was come out of Judaea into Galilee."],
["358", "Luke 4:16", "And he came to Nazareth, where he had been brought up: and, as his custom was, he went into the synagogue on the sabbath day, and stood up for to read."],
["359", "Luke 4:17", "And there was delivered unto him the book of the prophet Esaias. And when he had opened the book, he found the place where it was written,"],
["360", "Luke 4:18", "The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor; he hath sent me to heal the brokenhearted, to preach deliverance to the captives, and recovering of sight to the blind, to set at liberty them that are bruised,"],
["361", "Luke 4:19", "To preach the acceptable year of the Lord."],
["362", "Luke 4:20", "And he closed the book, and he gave it again to the minister, and sat down. And the eyes of all them that were in the synagogue were fastened on him."],
["363", "Luke 4:21", "And he began to say unto them, This day is this scripture fulfilled in your ears."],
["364", "Luke 4:22", "And all bare him witness, and wondered at the gracious words which proceeded out of his mouth. And they said, Is not this Joseph's son?"],
["365", "Luke 4:23", "And he said unto them, Ye will surely say unto me this proverb, Physician, heal thyself: whatsoever we have heard done in Capernaum, do also here in thy country."],
["366", "Luke 4:24", "And he said, Verily I say unto you, No prophet is accepted in his own country."],
["367", "Luke 4:25", "But I tell you of a truth, many widows were in Israel in the days of Elias, when the heaven was shut up three years and six months, when great famine was throughout all the land;"],
["368", "Luke 4:26", "But unto none of them was Elias sent, save unto Sarepta, a city of Sidon, unto a woman that was a widow."],
["369", "Luke 4:27", "And many lepers were in Israel in the time of Eliseus the prophet; and none of them was cleansed, saving Naaman the Syrian."],
["370", "Luke 4:28", "And all they in the synagogue, when they heard these things, were filled with wrath,"],
["371", "Luke 4:29", "And rose up, and thrust him out of the city, and led him unto the brow of the hill whereon their city was built, that they might cast him down headlong."],
["372", "Luke 4:30", "But he passing through the midst of them went his way,"],
["373", "Luke 4:31", "And came down to Capernaum, a city of Galilee, and taught them on the sabbath days."],
["374", "Matthew 4:13", "And leaving Nazareth, he came and dwelt in Capernaum, which is upon the sea coast, in the borders of Zabulon and Nephthalim:"],
["375", "Matthew 4:14", "That it might be fulfilled which was spoken by Esaias the prophet, saying,"],
["376", "Matthew 4:15", "The land of Zabulon, and the land of Nephthalim, by the way of the sea, beyond Jordan, Galilee of the Gentiles;"],
["377", "Matthew 4:16", "The people which sat in darkness saw great light; and to them which sat in the region and shadow of death light is sprung up."],
["378", "Luke 5:1", "And it came to pass, that, as the people pressed upon him to hear the word of God, he stood by the lake of Gennesaret,"],
["379", "Luke 5:2", "And saw two ships standing by the lake: but the fishermen were gone out of them, and were washing their nets."],
["380", "Luke 5:3", "And he entered into one of the ships, which was Simon's, and prayed him that he would thrust out a little from the land. And he sat down, and taught the people out of the ship."],
["381", "Luke 5:4", "Now when he had left speaking, he said unto Simon, Launch out into the deep, and let down your nets for a draught."],
["382", "Luke 5:5", "And Simon answering said unto him, Master, we have toiled all the night, and have taken nothing: nevertheless at thy word I will let down the net."],
["383", "Luke 5:6", "And when they had this done, they inclosed a great multitude of fishes: and their net brake."],
["384", "Luke 5:7", "And they beckoned unto their partners, which were in the other ship, that they should come and help them. And they came, and filled both the ships, so that they began to sink."],
["385", "Luke 5:8", "When Simon Peter saw it, he fell down at Jesus' knees, saying, Depart from me; for I am a sinful man, O Lord."],
["386", "Luke 5:9", "For he was astonished, and all that were with him, at the draught of the fishes which they had taken:"],
["387", "Luke 5:10", "And so was also James, and John, the sons of Zebedee, which were partners with Simon. And Jesus said unto Simon, Fear not; from henceforth thou shalt catch men."],
["388", "Luke 5:11", "And when they had brought their ships to land, they forsook all, and followed him."],
["389", "Mark 1:21", "And they went into Capernaum; and straightway on the sabbath day he entered into the synagogue, and taught."],
["390", "Mark 1:22", "And they were astonished at his doctrine: for he taught them as one that had authority, and not as the scribes."],
["391", "Mark 1:23", "And there was in their synagogue a man with an unclean spirit; and he cried out,"],
["392", "Mark 1:24", "Saying, Let us alone; what have we to do with thee, thou Jesus of Nazareth? art thou come to destroy us? I know thee who thou art, the Holy One of God."],
["393", "Mark 1:25", "And Jesus rebuked him, saying, Hold thy peace, and come out of him."],
["394", "Mark 1:26", "And when the unclean spirit had torn him, and cried with a loud voice, he came out of him."],
["395", "Mark 1:27", "And they were all amazed, insomuch that they questioned among themselves, saying, What thing is this? what new doctrine is this? for with authority commandeth he even the unclean spirits, and they do obey him."],
["396", "Mark 1:28", "And immediately his fame spread abroad throughout all the region round about Galilee."],
["397", "Mark 1:29", "And forthwith, when they were come out of the synagogue, they entered into the house of Simon and Andrew, with James and John."],
["398", "Mark 1:30", "But Simon's wife's mother lay sick of a fever, and anon they tell him of her."],
["399", "Mark 1:31", "And he came and took her by the hand, and lifted her up; and immediately the fever left her, and she ministered unto them."],
["400", "Mark 1:32", "And at even, when the sun did set, they brought unto him all that were diseased, and them that were possessed with devils."],
["401", "Mark 1:33", "And all the city was gathered together at the door."],
["402", "Mark 1:34", "And he healed many that were sick of divers diseases, and cast out many devils; and suffered not the devils to speak, because they knew him."],
["403", "Matthew 4:23", "And Jesus went about all Galilee, teaching in their synagogues, and preaching the gospel of the kingdom, and healing all manner of sickness and all manner of disease among the people."],
["404", "Matthew 4:24", "And his fame went throughout all Syria: and they brought unto him all sick people that were taken with divers diseases and torments, and those which were possessed with devils, and those which were lunatick, and those that had the palsy; and he healed them."],
["405", "Matthew 4:25", "And there followed him great multitudes of people from Galilee, and from Decapolis, and from Jerusalem, and from Judaea, and from beyond Jordan."],
["406", "Luke 5:12", "And it came to pass, when he was in a certain city, behold a man full of leprosy: who seeing Jesus fell on his face, and besought him, saying, Lord, if thou wilt, thou canst make me clean."],
["407", "Luke 5:13", "And he put forth his hand, and touched him, saying, I will: be thou clean. And immediately the leprosy departed from him."],
["408", "Luke 5:14", "And he charged him to tell no man: but go, and shew thyself to the priest, and offer for thy cleansing, according as Moses commanded, for a testimony unto them."],
["409", "Luke 5:15", "But so much the more went there a fame abroad of him: and great multitudes came together to hear, and to be healed by him of their infirmities."],
["410", "Luke 5:16", "And he withdrew himself into the wilderness, and prayed."],
["411", "Mark 2:1", "And again he entered into Capernaum after some days; and it was noised that he was in the house."],
["412", "Mark 2:2", "And straightway many were gathered together, insomuch that there was no room to receive them, no, not so much as about the door: and he preached the word unto them."],
["413", "Mark 2:3", "And they come unto him, bringing one sick of the palsy, which was borne of four."],
["414", "Mark 2:4", "And when they could not come nigh unto him for the press, they uncovered the roof where he was: and when they had broken it up, they let down the bed wherein the sick of the palsy lay."],
["415", "Mark 2:5", "When Jesus saw their faith, he said unto the sick of the palsy, Son, thy sins be forgiven thee."],
["416", "Mark 2:6", "But there were certain of the scribes sitting there, and reasoning in their hearts,"],
["417", "Mark 2:7", "Why doth this man thus speak blasphemies? who can forgive sins but God only?"],
["418", "Mark 2:8", "And immediately when Jesus perceived in his spirit that they so reasoned within themselves, he said unto them, Why reason ye these things in your hearts?"],
["419", "Mark 2:9", "Whether is it easier to say to the sick of the palsy, Thy sins be forgiven thee; or to say, Arise, and take up thy bed, and walk?"],
["420", "Mark 2:10", "But that ye may know that the Son of man hath power on earth to forgive sins, (he saith to the sick of the palsy,)"],
["421", "Mark 2:11", "I say unto thee, Arise, and take up thy bed, and go thy way into thine house."],
["422", "Mark 2:12", "And immediately he arose, took up the bed, and went forth before them all; insomuch that they were all amazed, and glorified God, saying, We never saw it on this fashion."],
["423", "Mark 2:13", "And he went forth again by the sea side; and all the multitude resorted unto him, and he taught them."],
["424", "Mark 2:14", "And as he passed by, he saw Levi the son of Alphaeus sitting at the receipt of custom, and said unto him, Follow me. And he arose and followed him."],
["425", "Mark 2:15", "And it came to pass, that, as Jesus sat at meat in his house, many publicans and sinners sat also together with Jesus and his disciples: for there were many, and they followed him."],
["426", "Mark 2:16", "And when the scribes and Pharisees saw him eat with publicans and sinners, they said unto his disciples, How is it that he eateth and drinketh with publicans and sinners?"],
["427", "Mark 2:17", "When Jesus heard it, he saith unto them, They that are whole have no need of the physician, but they that are sick: I came not to call the righteous, but sinners to repentance."],
["428", "Luke 5:33", "And they said unto him, Why do the disciples of John fast often, and make prayers, and likewise the disciples of the Pharisees; but thine eat and drink?"],
["429", "Luke 5:34", "And he said unto them, Can ye make the children of the bridechamber fast, while the bridegroom is with them?"],
["430", "Luke 5:35", "But the days will come, when the bridegroom shall be taken away from them, and then shall they fast in those days."],
["431", "Luke 5:36", "And he spake also a parable unto them; No man putteth a piece of a new garment upon an old; if otherwise, then both the new maketh a rent, and the piece that was taken out of the new agreeth not with the old."],
["432", "Luke 5:37", "And no man putteth new wine into old bottles; else the new wine will burst the bottles, and be spilled, and the bottles shall perish."],
["433", "Luke 5:38", "But new wine must be put into new bottles; and both are preserved."],
["434", "Luke 5:39", "No man also having drunk old wine straightway desireth new: for he saith, The old is better."],
["435", "John 5:1", "After this there was a feast of the Jews; and Jesus went up to Jerusalem."],
["436", "John 5:2", "Now there is at Jerusalem by the sheep market a pool, which is called in the Hebrew tongue Bethesda, having five porches."],
["437", "John 5:3", "In these lay a great multitude of impotent folk, of blind, halt, withered, waiting for the moving of the water."],
["438", "John 5:4", "For an angel went down at a certain season into the pool, and troubled the water: whosoever then first after the troubling of the water stepped in was made whole of whatsoever disease he had."],
["439", "John 5:5", "And a certain man was there, which had an infirmity thirty and eight years."],
["440", "John 5:6", "When Jesus saw him lie, and knew that he had been now a long time in that case, he saith unto him, Wilt thou be made whole?"],
["441", "John 5:7", "The impotent man answered him, Sir, I have no man, when the water is troubled, to put me into the pool: but while I am coming, another steppeth down before me."],
["442", "John 5:8", "Jesus saith unto him, Rise, take up thy bed, and walk."],
["443", "John 5:9", "And immediately the man was made whole, and took up his bed, and walked: and on the same day was the sabbath."],
["444", "John 5:10", "The Jews therefore said unto him that was cured, It is the sabbath day: it is not lawful for thee to carry thy bed."],
["445", "John 5:11", "He answered them, He that made me whole, the same said unto me, Take up thy bed, and walk."],
["446", "John 5:12", "Then asked they him, What man is that which said unto thee, Take up thy bed, and walk?"],
["447", "John 5:13", "And he that was healed wist not who it was: for Jesus had conveyed himself away, a multitude being in that place."],
["448", "John 5:14", "Afterward Jesus findeth him in the temple, and said unto him, Behold, thou art made whole: sin no more, lest a worse thing come unto thee."],
["449", "John 5:15", "The man departed, and told the Jews that it was Jesus, which had made him whole."],
["450", "John 5:16", "And therefore did the Jews persecute Jesus, and sought to slay him, because he had done these things on the sabbath day."],
["451", "John 5:17", "But Jesus answered them, My Father worketh hitherto, and I work."],
["452", "John 5:18", "Therefore the Jews sought the more to kill him, because he not only had broken the sabbath, but said also that God was his Father, making himself equal with God."],
["453", "John 5:19", "Then answered Jesus and said unto them, Verily, verily, I say unto you, The Son can do nothing of himself, but what he seeth the Father do: for what things soever he doeth, these also doeth the Son likewise."],
["454", "John 5:20", "For the Father loveth the Son, and sheweth him all things that himself doeth: and he will shew him greater works than these, that ye may marvel."],
["455", "John 5:21", "For as the Father raiseth up the dead, and quickeneth them; even so the Son quickeneth whom he will."],
["456", "John 5:22", "For the Father judgeth no man, but hath committed all judgment unto the Son:"],
["457", "John 5:23", "That all men should honour the Son, even as they honour the Father. He that honoureth not the Son honoureth not the Father which hath sent him."],
["458", "John 5:24", "Verily, verily, I say unto you, He that heareth my word, and believeth on him that sent me, hath everlasting life, and shall not come into condemnation; but is passed from death unto life."],
["459", "John 5:25", "Verily, verily, I say unto you, The hour is coming, and now is, when the dead shall hear the voice of the Son of God: and they that hear shall live."],
["460", "John 5:26", "For as the Father hath life in himself; so hath he given to the Son to have life in himself;"],
["461", "John 5:27", "And hath given him authority to execute judgment also, because he is the Son of man."],
["462", "John 5:28", "Marvel not at this: for the hour is coming, in the which all that are in the graves shall hear his voice,"],
["463", "John 5:29", "And shall come forth; they that have done good, unto the resurrection of life; and they that have done evil, unto the resurrection of damnation."],
["464", "John 5:30", "I can of mine own self do nothing: as I hear, I judge: and my judgment is just; because I seek not mine own will, but the will of the Father which hath sent me."],
["465", "John 5:31", "If I bear witness of myself, my witness is not true."],
["466", "John 5:32", "There is another that beareth witness of me; and I know that the witness which he witnesseth of me is true."],
["467", "John 5:33", "Ye sent unto John, and he bare witness unto the truth."],
["468", "John 5:34", "But I receive not testimony from man: but these things I say, that ye might be saved."],
["469", "John 5:35", "He was a burning and a shining light: and ye were willing for a season to rejoice in his light."],
["470", "John 5:36", "But I have greater witness than that of John: for the works which the Father hath given me to finish, the same works that I do, bear witness of me, that the Father hath sent me."],
["471", "John 5:37", "And the Father himself, which hath sent me, hath borne witness of me. Ye have neither heard his voice at any time, nor seen his shape."],
["472", "John 5:38", "And ye have not his word abiding in you: for whom he hath sent, him ye believe not."],
["473", "John 5:39", "Search the scriptures; for in them ye think ye have eternal life: and they are they which testify of me."],
["474", "John 5:40", "And ye will not come to me, that ye might have life."],
["475", "John 5:41", "I receive not honour from men."],
["476", "John 5:42", "But I know you, that ye have not the love of God in you."],
["477", "John 5:43", "I am come in my Father's name, and ye receive me not: if another shall come in his own name, him ye will receive."],
["478", "John 5:44", "How can ye believe, which receive honour one of another, and seek not the honour that cometh from God only?"],
["479", "John 5:45", "Do not think that I will accuse you to the Father: there is one that accuseth you, even Moses, in whom ye trust."],
["480", "John 5:46", "For had ye believed Moses, ye would have believed me: for he wrote of me."],
["481", "John 5:47", "But if ye believe not his writings, how shall ye believe my words?"],
["482", "Matthew 12:1", "At that time Jesus went on the sabbath day through the corn; and his disciples were an hungred, and began to pluck the ears of corn, and to eat."],
["483", "Matthew 12:2", "But when the Pharisees saw it, they said unto him, Behold, thy disciples do that which is not lawful to do upon the sabbath day."],
["484", "Matthew 12:3", "But he said unto them, Have ye not read what David did, when he was an hungred, and they that were with him;"],
["485", "Matthew 12:4", "How he entered into the house of God, and did eat the shewbread, which was not lawful for him to eat, neither for them which were with him, but only for the priests?"],
["486", "Matthew 12:5", "Or have ye not read in the law, how that on the sabbath days the priests in the temple profane the sabbath, and are blameless?"],
["487", "Matthew 12:6", "But I say unto you, That in this place is one greater than the temple."],
["488", "Matthew 12:7", "But if ye had known what this meaneth, I will have mercy, and not sacrifice, ye would not have condemned the guiltless."],
["489", "Matthew 12:8", "For the Son of man is Lord even of the sabbath day."],
["490", "Matthew 12:9", "And when he was departed thence, he went into their synagogue:"],
["491", "Matthew 12:10", "And, behold, there was a man which had his hand withered. And they asked him, saying, Is it lawful to heal on the sabbath days? that they might accuse him."],
["492", "Matthew 12:11", "And he said unto them, What man shall there be among you, that shall have one sheep, and if it fall into a pit on the sabbath day, will he not lay hold on it, and lift it out?"],
["493", "Matthew 12:12", "How much then is a man better than a sheep? Wherefore it is lawful to do well on the sabbath days."],
["494", "Matthew 12:13", "Then saith he to the man, Stretch forth thine hand. And he stretched it forth; and it was restored whole, like as the other."],
["495", "Matthew 12:14", "Then the Pharisees went out, and held a council against him, how they might destroy him."],
["496", "Matthew 12:15", "But when Jesus knew it, he withdrew himself from thence: and great multitudes followed him, and he healed them all;"],
["497", "Matthew 12:16", "And charged them that they should not make him known:"],
["498", "Matthew 12:17", "That it might be fulfilled which was spoken by Esaias the prophet, saying,"],
["499", "Matthew 12:18", "Behold my servant, whom I have chosen; my beloved, in whom my soul is well pleased: I will put my spirit upon him, and he shall shew judgment to the Gentiles."],
["500", "Matthew 12:19", "He shall not strive, nor cry; neither shall any man hear his voice in the streets."],
["501", "Matthew 12:20", "A bruised reed shall he not break, and smoking flax shall he not quench, till he send forth judgment unto victory."],
["502", "Matthew 12:21", "And in his name shall the Gentiles trust."],
["503", "Luke 6:12", "And it came to pass in those days, that he went out into a mountain to pray, and continued all night in prayer to God."],
["504", "Luke 6:13", "And when it was day, he called unto him his disciples: and of them he chose twelve, whom also he named apostles;"],
["505", "Luke 6:14", "Simon, (whom he also named Peter,) and Andrew his brother, James and John, Philip and Bartholomew,"],
["506", "Luke 6:15", "Matthew and Thomas, James the son of Alphaeus, and Simon called Zelotes,"],
["507", "Luke 6:16", "And Judas the brother of James, and Judas Iscariot, which also was the traitor."],
["508", "Luke 6:17", "And he came down with them, and stood in the plain, and the company of his disciples, and a great multitude of people out of all Judaea and Jerusalem, and from the sea coast of Tyre and Sidon, which came to hear him, and to be healed of their diseases;"],
["509", "Luke 6:18", "And they that were vexed with unclean spirits: and they were healed."],
["510", "Luke 6:19", "And the whole multitude sought to touch him: for there went virtue out of him, and healed them all."]];
