/*
Greetings to whomever was curious about this code.

I know it is a horrible idea to manually encode the breakpoints and verses, but I made this site in a school computer lab in about half an hour in 2022, and I do not wish to refactor at this time.


Thank you,

Joshua Bays
*/

let masterList = [
['240', 'John 1:51', 'And he saith unto him, Verily, verily, I say unto …God ascending and descending upon the Son of man.'],
['238', 'John 1:49', 'Nathanael answered and saith unto him, Rabbi, thou art the Son of God; thou art the King of Israel.'],
['236', 'John 1:47', 'Jesus saw Nathanael coming to him, and saith of hi… Behold an Israelite indeed, in whom is no guile!'],
['235', 'John 1:46', 'And Nathanael said unto him, Can there any good th…of Nazareth? Philip saith unto him, Come and see.'],
['234', 'John 1:45', 'Philip findeth Nathanael, and saith unto him, We h… did write, Jesus of Nazareth, the son of Joseph.'],
['230', 'John 1:41', 'He first findeth his own brother Simon, and saith …Messias, which is, being interpreted, the Christ.'],
['229', 'John 1:40', "One of the two which heard John speak, and followed him, was Andrew, Simon Peter's brother."],
['228', 'John 1:39', 'He saith unto them, Come and see. They came and sa…th him that day: for it was about the tenth hour.'],
['227', 'John 1:38', 'Then Jesus turned, and saw them following, and sai… being interpreted, Master,) where dwellest thou?'],
['224', 'John 1:35', 'Again the next day after John stood, and two of his disciples;'],
['223', 'John 1:34', 'And I saw, and bare record that this is the Son of God.'],
['222', 'John 1:33', 'And I knew him not: but he that sent me to baptize…e same is he which baptizeth with the Holy Ghost.'],
['221', 'John 1:32', 'And John bare record, saying, I saw the Spirit des…g from heaven like a dove, and it abode upon him.'],
['220', 'John 1:31', 'And I knew him not: but that he should be made man…Israel, therefore am I come baptizing with water.'],
['216', 'John 1:27', "He it is, who coming after me is preferred before … whose shoe's latchet I am not worthy to unloose."],
['215', 'John 1:26', 'John answered them, saying, I baptize with water: …t there standeth one among you, whom ye know not;'],
['214', 'John 1:25', 'And they asked him, and said unto him, Why baptize…not that Christ, nor Elias, neither that prophet?'],
['210', 'John 1:21', 'And they asked him, What then? Art thou Elias? And… not. Art thou that prophet? And he answered, No.'],
['209', 'John 1:20', 'And he confessed, and denied not; but confessed, I am not the Christ.'],
['208', 'John 1:19', 'And this is the record of John, when the Jews sent… Levites from Jerusalem to ask him, Who art thou?'],
['204', 'Matthew 4:8', 'Again, the devil taketh him up into an exceeding h…the kingdoms of the world, and the glory of them;'],
['201', 'Matthew 4:5', 'Then the devil taketh him up into the holy city, and setteth him on a pinnacle of the temple,'],
['200', 'Matthew 4:4', 'But he answered and said, It is written, Man shall…ery word that proceedeth out of the mouth of God.'],
['199', 'Matthew 4:3', 'And when the tempter came to him, he said, If thou… of God, command that these stones be made bread.'],
['197', 'Matthew 4:1', 'Then was Jesus led up of the Spirit into the wilderness to be tempted of the devil.'],
['194', 'Matthew 3:16', 'And Jesus, when he was baptized, went up straightw…od descending like a dove, and lighting upon him:'],
['192', 'Matthew 3:14', 'But John forbad him, saying, I have need to be baptized of thee, and comest thou to me?'],
['191', 'Matthew 3:13', 'Then cometh Jesus from Galilee to Jordan unto John, to be baptized of him.'],
['190', 'Luke 3:18', 'And many other things in his exhortation preached he unto the people.'],
['188', 'Luke 3:16', 'John answered, saying unto them all, I indeed bapt…ll baptize you with the Holy Ghost and with fire:'],
['187', 'Luke 3:15', 'And as the people were in expectation, and all men…arts of John, whether he were the Christ, or not;'],
['186', 'Matthew 3:10', 'And now also the axe is laid unto the root of the … good fruit is hewn down, and cast into the fire.'],
['183', 'Matthew 3:7', 'But when he saw many of the Pharisees and Sadducee…o hath warned you to flee from the wrath to come?'],
['182', 'Matthew 3:6', 'And were baptized of him in Jordan, confessing their sins.'],
['181', 'Matthew 3:5', 'Then went out to him Jerusalem, and all Judaea, and all the region round about Jordan,'],
['180', 'Matthew 3:4', "And the same John had his raiment of camel's hair,…s loins; and his meat was locusts and wild honey."],
['179', 'Matthew 3:3', 'For this is he that was spoken of by the prophet E… ye the way of the Lord, make his paths straight.'],
['174', 'Luke 2:50', 'And they understood not the saying which he spake unto them.'],
['172', 'Luke 2:48', 'And when they saw him, they were amazed: and his m…old, thy father and I have sought thee sorrowing.'],
['171', 'Luke 2:47', 'And all that heard him were astonished at his understanding and answers.'],
['170', 'Luke 2:46', 'And it came to pass, that after three days they fo…rs, both hearing them, and asking them questions.'],
['169', 'Luke 2:45', 'And when they found him not, they turned back again to Jerusalem, seeking him.'],
['168', 'Luke 2:44', 'But they, supposing him to have been in the compan…sought him among their kinsfolk and acquaintance.'],
['167', 'Luke 2:43', 'And when they had fulfilled the days, as they retu…usalem; and Joseph and his mother knew not of it.'],
['166', 'Luke 2:42', 'And when he was twelve years old, they went up to Jerusalem after the custom of the feast.'],
['163', 'Matthew 2:23', 'And he came and dwelt in a city called Nazareth: t…n by the prophets, He shall be called a Nazarene.'],
['161', 'Matthew 2:21', 'And he arose, and took the young child and his mother, and came into the land of Israel.'],
['159', 'Matthew 2:19', 'But when Herod was dead, behold, an angel of the Lord appeareth in a dream to Joseph in Egypt,'],
['155', 'Matthew 2:15', 'And was there until the death of Herod: that it mi…ophet, saying, Out of Egypt have I called my son.'],
['152', 'Matthew 2:12', 'And being warned of God in a dream that they shoul…they departed into their own country another way.'],
['151', 'Matthew 2:11', 'And when they were come into the house, they saw t…nto him gifts; gold, and frankincense, and myrrh.'],
['149', 'Matthew 2:9', 'When they had heard the king, they departed; and, …it came and stood over where the young child was.'],
['148', 'Matthew 2:8', 'And he sent them to Bethlehem, and said, Go and se…word again, that I may come and worship him also.'],
['147', 'Matthew 2:7', 'Then Herod, when he had privily called the wise me…d of them diligently what time the star appeared.'],
['144', 'Matthew 2:4', 'And when he had gathered all the chief priests and… he demanded of them where Christ should be born.'],
['142', 'Matthew 2:2', 'Saying, Where is he that is born King of the Jews?…is star in the east, and are come to worship him.'],
['141', 'Matthew 2:1', 'Now when Jesus was born in Bethlehem of Judaea in …, there came wise men from the east to Jerusalem,'],
['138', 'Luke 2:36', 'And there was one Anna, a prophetess, the daughter…d with an husband seven years from her virginity;'],
['137', 'Luke 2:35', '(Yea, a sword shall pierce through thy own soul al…that the thoughts of many hearts may be revealed.'],
['134', 'Luke 2:32', 'A light to lighten the Gentiles, and the glory of thy people Israel.'],
['133', 'Luke 2:31', 'Which thou hast prepared before the face of all people;'],
['127', 'Luke 2:25', 'And, behold, there was a man in Jerusalem, whose n…ation of Israel: and the Holy Ghost was upon him.'],
['125', 'Luke 2:23', '(As it is written in the law of the LORD, Every ma…eneth the womb shall be called holy to the Lord;)'],
['124', 'Luke 2:22', 'And when the days of her purification according to…ght him to Jerusalem, to present him to the Lord;'],
['123', 'Luke 2:21', 'And when eight days were accomplished for the circ…of the angel before he was conceived in the womb.'],
['122', 'Luke 2:20', 'And the shepherds returned, glorifying and praisin…hey had heard and seen, as it was told unto them.'],
['121', 'Luke 2:19', 'But Mary kept all these things, and pondered them in her heart.'],
['120', 'Luke 2:18', 'And all they that heard it wondered at those things which were told them by the shepherds.'],
['119', 'Luke 2:17', 'And when they had seen it, they made known abroad …saying which was told them concerning this child.'],
['118', 'Luke 2:16', 'And they came with haste, and found Mary, and Joseph, and the babe lying in a manger.'],
['117', 'Luke 2:15', 'And it came to pass, as the angels were gone away … to pass, which the Lord hath made known unto us.'],
['116', 'Luke 2:14', 'Glory to God in the highest, and on earth peace, good will toward men.'],
['115', 'Luke 2:13', 'And suddenly there was with the angel a multitude of the heavenly host praising God, and saying,'],
['112', 'Luke 2:10', 'And the angel said unto them, Fear not: for, behol…dings of great joy, which shall be to all people.'],
['111', 'Luke 2:9', 'And, lo, the angel of the Lord came upon them, and…hone round about them: and they were sore afraid.'],
['109', 'Luke 2:7', 'And she brought forth her firstborn son, and wrapp…r; because there was no room for them in the inn.'],
['108', 'Luke 2:6', 'And so it was, that, while they were there, the days were accomplished that she should be delivered.'],
['106', 'Luke 2:4', 'And Joseph also went up from Galilee, out of the c…ecause he was of the house and lineage of David:)'],
['104', 'Luke 2:2', '(And this taxing was first made when Cyrenius was governor of Syria.)'],
['101', 'Matthew 1:24', 'Then Joseph being raised from sleep did as the ang… Lord had bidden him, and took unto him his wife:'],
['100', 'Matthew 1:23', 'Behold, a virgin shall be with child, and shall br…mmanuel, which being interpreted is, God with us.'],
['99', 'Matthew 1:22', 'Now all this was done, that it might be fulfilled …ch was spoken of the Lord by the prophet, saying,'],
['98', 'Matthew 1:21', 'And she shall bring forth a son, and thou shalt ca…US: for he shall save his people from their sins.'],
['96', 'Matthew 1:19', 'Then Joseph her husband, being a just man, and not…lick example, was minded to put her away privily.'],
['95', 'Matthew 1:18', 'Now the birth of Jesus Christ was on this wise: Wh…ther, she was found with child of the Holy Ghost.'],
['94', 'Luke 1:80', 'And the child grew, and waxed strong in spirit, an… deserts till the day of his shewing unto Israel.'],
['93', 'Luke 1:79', 'To give light to them that sit in darkness and in …f death, to guide our feet into the way of peace.'],
['92', 'Luke 1:78', 'Through the tender mercy of our God; whereby the dayspring from on high hath visited us,'],
['91', 'Luke 1:77', 'To give knowledge of salvation unto his people by the remission of their sins,'],
['87', 'Luke 1:73', 'The oath which he sware to our father Abraham,'],
['85', 'Luke 1:71', 'That we should be saved from our enemies, and from the hand of all that hate us;'],
['82', 'Luke 1:68', 'Blessed be the Lord God of Israel; for he hath visited and redeemed his people,'],
['77', 'Luke 1:63', 'And he asked for a writing table, and wrote, saying, His name is John. And they marvelled all.'],
['76', 'Luke 1:62', 'And they made signs to his father, how he would have him called.'],
['75', 'Luke 1:61', 'And they said unto her, There is none of thy kindred that is called by this name.'],
['74', 'Luke 1:60', 'And his mother answered and said, Not so; but he shall be called John.'],
['73', 'Luke 1:59', 'And it came to pass, that on the eighth day they c…lled him Zacharias, after the name of his father.'],
['72', 'Luke 1:58', 'And her neighbours and her cousins heard how the L…great mercy upon her; and they rejoiced with her.'],
['71', 'Luke 1:57', "Now Elisabeth's full time came that she should be delivered; and she brought forth a son."],
['70', 'Luke 1:56', 'And Mary abode with her about three months, and returned to her own house.'],
[100 … 135]
['68', 'Luke 1:54', 'He hath holpen his servant Israel, in remembrance of his mercy;'],
['67', 'Luke 1:53', 'He hath filled the hungry with good things; and the rich he hath sent empty away.'],
['64', 'Luke 1:50', 'And his mercy is on them that fear him from generation to generation.'],
['62', 'Luke 1:48', 'For he hath regarded the low estate of his handmai…henceforth all generations shall call me blessed.'],
['60', 'Luke 1:46', 'And Mary said, My soul doth magnify the Lord,'],
['59', 'Luke 1:45', 'And blessed is she that believed: for there shall …f those things which were told her from the Lord.'],
['57', 'Luke 1:43', 'And whence is this to me, that the mother of my Lord should come to me?'],
['55', 'Luke 1:41', 'And it came to pass, that, when Elisabeth heard th…mb; and Elisabeth was filled with the Holy Ghost:'],
['53', 'Luke 1:39', 'And Mary arose in those days, and went into the hill country with haste, into a city of Juda;'],
['50', 'Luke 1:36', 'And, behold, thy cousin Elisabeth, she hath also c… the sixth month with her, who was called barren.'],
['48', 'Luke 1:34', 'Then said Mary unto the angel, How shall this be, seeing I know not a man?'],
['47', 'Luke 1:33', 'And he shall reign over the house of Jacob for ever; and of his kingdom there shall be no end.'],
['41', 'Luke 1:27', "To a virgin espoused to a man whose name was Josep…e house of David; and the virgin's name was Mary."],
['40', 'Luke 1:26', 'And in the sixth month the angel Gabriel was sent from God unto a city of Galilee, named Nazareth,'],
['38', 'Luke 1:24', 'And after those days his wife Elisabeth conceived, and hid herself five months, saying,'],
['35', 'Luke 1:21', 'And the people waited for Zacharias, and marvelled that he tarried so long in the temple.'],
['34', 'Luke 1:20', 'And, behold, thou shalt be dumb, and not able to s… words, which shall be fulfilled in their season.'],
['32', 'Luke 1:18', 'And Zacharias said unto the angel, Whereby shall I…m an old man, and my wife well stricken in years.'],
['31', 'Luke 1:17', 'And he shall go before him in the spirit and power…st; to make ready a people prepared for the Lord.'],
['28', 'Luke 1:14', 'And thou shalt have joy and gladness; and many shall rejoice at his birth.'],
['26', 'Luke 1:12', 'And when Zacharias saw him, he was troubled, and fear fell upon him.'],
['25', 'Luke 1:11', 'And there appeared unto him an angel of the Lord standing on the right side of the altar of incense.'],
['24', 'Luke 1:10', 'And the whole multitude of the people were praying without at the time of incense.'],
['23', 'Luke 1:9', "According to the custom of the priest's office, hi…incense when he went into the temple of the Lord."],
['21', 'Luke 1:7', 'And they had no child, because that Elisabeth was …n, and they both were now well stricken in years.'],
['18', 'John 1:18', 'No man hath seen God at any time; the only begotte…in the bosom of the Father, he hath declared him.'],
['17', 'John 1:17', 'For the law was given by Moses, but grace and truth came by Jesus Christ.'],
['13', 'John 1:13', 'Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.'],
['10', 'John 1:10', 'He was in the world, and the world was made by him, and the world knew him not.'],
['9', 'John 1:9', 'That was the true Light, which lighteth every man that cometh into the world.'],
['8', 'John 1:8', 'He was not that Light, but was sent to bear witness of that Light.'],
['7', 'John 1:7', 'The same came for a witness, to bear witness of the Light, that all men through him might believe.'],
['5', 'John 1:5', 'And the light shineth in darkness; and the darkness comprehended it not.'],
['4', 'John 1:4', 'In him was life; and the life was the light of men.'],
['3', 'John 1:3', 'All things were made by him; and without him was not any thing made that was made.'],
['2', 'John 1:2', 'The same was in the beginning with God.']];
